# How to use this NB:

Only thing you need to run is the imports cell below, and the "def concatenate_logs" function. 

Then copy paste the for loop, replacing the file paths for each directory you want to concatenate logs for. 

In [1]:
import pandas as pd
import numpy as np

## Incomplete A_bdnn files

Conclusion: mcmc files that time out do so asymmetrically: the mcmc, sp_rates, ex_rates, and per_species_rates logs all have different numbers of samples at the time of timeout

In [5]:
a_bdnn_rep_4 = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_4_G_BDS_BDNN_4_2Tc_mcmc.log", sep="\t", header=0)
a_bdnn_rep_4.describe()

,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Yelaphomte_TE,Yimenosaurus_TE,Youngetta_TE,Youngina_TE,Youngosuchus_TE,Yunguisaurus_TE,Yunnanosaurus_TE,Zanclodon_TE,Zhongjiania_TE,Zupaysaurus_TE
count,9.693000e+03,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,...,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000
mean,4.846000e+07,-16921.714012,-2200.535270,-10616.733448,-4104.445295,0.686177,5.215353,0.878803,1.310975,2.430629,...,49.783495,24.385640,75.266885,76.284624,71.585801,61.359895,25.673319,27.263383,79.307226,47.777007
std,2.798272e+07,83.369567,13.142674,48.843440,51.939738,0.228424,0.360970,0.180667,0.344515,0.341176,...,0.958016,0.335684,0.375294,1.305898,0.457496,1.538418,0.513775,1.631867,0.562239,0.868704
min,0.000000e+00,-21792.450507,-2237.064142,-11981.405312,-7738.214920,0.188454,0.370792,0.370792,0.370792,0.370792,...,41.472211,21.107097,71.768193,64.341286,67.302719,51.900640,19.556576,18.030161,72.220950,41.919526
25%,2.423000e+07,-16957.780476,-2208.012767,-10646.210464,-4113.972388,0.530206,4.977896,0.740142,1.067608,2.196133,...,49.550209,24.262202,75.162315,75.811032,71.471557,60.736297,25.542419,26.445395,79.150294,47.498972
50%,4.846000e+07,-16918.003652,-2201.152604,-10615.929466,-4100.129786,0.652367,5.216158,0.873919,1.280274,2.406863,...,50.123677,24.490054,75.398168,76.715512,71.750083,61.915054,25.843795,27.706333,79.465298,48.089558
75%,7.269000e+07,-16878.386231,-2194.579236,-10585.247380,-4087.214055,0.805875,5.450380,1.009955,1.522991,2.637751,...,50.384068,24.621657,75.512523,77.184692,71.879284,62.487983,25.994106,28.546175,79.651815,48.374086
max,9.692000e+07,-16724.404910,-2072.830274,-10398.689248,-4028.669482,2.638998,6.729365,1.651070,4.113144,5.166731,...,50.522489,24.713129,75.567580,77.436463,71.936261,62.766438,26.106801,29.142904,79.791650,48.512072


In [15]:
a_bdnn_rep_4_sp_rates = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_4_G_BDS_BDNN_4_2Tc_sp_rates.log", sep="\t", header=0)
a_bdnn_rep_4_sp_rates.describe()



,0.7021791291715602,0.702179124256164,0.7021791187087707,0.7021791131613488,0.7021791076138986,0.7021791020664202,0.7021790965189137,0.7021790909713798,0.7021790854238181,0.7021790798762295,...,10,9,8,7,6,5,4,3,2,1
count,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,9693.000000,...,9693.0,9693.0,9693.0,9693.0,9693.0,9693.0,9693.0,9693.0,9693.0,9693.0
mean,0.322846,0.323297,0.323810,0.324328,0.324850,0.325376,0.325904,0.326433,0.326962,0.327491,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0
std,0.047138,0.046647,0.046081,0.045504,0.044915,0.044314,0.043702,0.043078,0.042442,0.041795,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,0.134854,0.134855,0.134857,0.134859,0.134861,0.134864,0.134866,0.134868,0.134870,0.134873,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0
25%,0.290628,0.291371,0.292275,0.293205,0.294078,0.295115,0.296074,0.297110,0.298044,0.299029,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0
50%,0.324802,0.325192,0.325588,0.326045,0.326593,0.327092,0.327469,0.327883,0.328423,0.328864,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0
75%,0.355585,0.355630,0.355694,0.355777,0.355888,0.355909,0.356027,0.356080,0.356219,0.356194,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0
max,0.515050,0.513531,0.511751,0.509897,0.507968,0.505959,0.503868,0.501690,0.499423,0.497063,...,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0


In [16]:
a_bdnn_rep_4_sp_rates.head()

,0.7021791291715602,0.702179124256164,0.7021791187087707,0.7021791131613488,0.7021791076138986,0.7021791020664202,0.7021790965189137,0.7021790909713798,0.7021790854238181,0.7021790798762295,...,10,9,8,7,6,5,4,3,2,1
0,0.141480,0.141485,0.141491,0.141497,0.141503,0.141509,0.141515,0.141522,0.141528,0.141534,...,10,9,8,7,6,5,4,3,2,1
1,0.139298,0.139337,0.139380,0.139424,0.139468,0.139512,0.139556,0.139600,0.139645,0.139690,...,10,9,8,7,6,5,4,3,2,1
2,0.148296,0.148297,0.148297,0.148298,0.148299,0.148299,0.148300,0.148301,0.148301,0.148302,...,10,9,8,7,6,5,4,3,2,1
3,0.148448,0.148449,0.148451,0.148452,0.148453,0.148455,0.148456,0.148458,0.148459,0.148460,...,10,9,8,7,6,5,4,3,2,1
4,0.140448,0.140450,0.140452,0.140455,0.140457,0.140459,0.140462,0.140464,0.140467,0.140469,...,10,9,8,7,6,5,4,3,2,1


In [17]:
a_bdnn_rep_4.shape, a_bdnn_rep_4_sp_rates.shape

((9693, 1576), (9693, 247))

In [27]:
a_bdnn_rep_4_ex_rates = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_4_G_BDS_BDNN_4_2Tc_ex_rates.log", sep="\t", header=0)
a_bdnn_rep_4_per_species_rates = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_4_G_BDS_BDNN_4_2Tc_per_species_rates.log", sep="\t", header=0)
a_bdnn_rep_4_ex_rates.shape, a_bdnn_rep_4_per_species_rates.shape


((9691, 247), (9694, 1521))

## Fully completed MCMC logs

seeing what size/shape they are, so I know what size/shape the concatenated ones should end up being.

Conclusion: mcmc logs and per_species_rates logs have 10k rows (samples), and sp_rates and ex_rates logs have 9,999 rows (samples)

In [24]:
# A fully completed A_bdnn
a_bdnn_tem_1 = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/temnospondyli/mcmc_no_predictors/A_bdnn_update/temnospondyli_pyrate_1_A_update_G_BDS_BDNN_4_2Tc_mcmc.log", sep="\t", header=0)
a_bdnn_tem_1_sp_rates = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/temnospondyli/mcmc_no_predictors/A_bdnn_update/temnospondyli_pyrate_1_A_update_G_BDS_BDNN_4_2Tc_sp_rates.log", sep="\t", header=0)
a_bdnn_tem_1_ex_rates = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/temnospondyli/mcmc_no_predictors/A_bdnn_update/temnospondyli_pyrate_1_A_update_G_BDS_BDNN_4_2Tc_ex_rates.log", sep="\t", header=0)
a_bdnn_tem_1_per_species_rates = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/temnospondyli/mcmc_no_predictors/A_bdnn_update/temnospondyli_pyrate_1_A_update_G_BDS_BDNN_4_2Tc_per_species_rates.log", sep="\t", header=0)

a_bdnn_tem_1.shape, a_bdnn_tem_1_sp_rates.shape, a_bdnn_tem_1_ex_rates.shape, a_bdnn_tem_1_per_species_rates.shape

((10000, 612), (9999, 269), (9999, 269), (10000, 557))

In [19]:
a_bdnn_tem_1_sp_rates.head()

,0.699868417722341,0.6998684194736766,0.6998684214834019,0.6998684234931282,0.6998684255028562,0.6998684275125848,0.6998684295223149,0.699868431532046,0.6998684335417787,0.6998684355515122,...,10,9,8,7,6,5,4,3,2,1
0,0.146344,0.146344,0.146345,0.146346,0.146347,0.146348,0.146349,0.146350,0.146351,0.146352,...,10,9,8,7,6,5,4,3,2,1
1,0.132279,0.132350,0.132429,0.132507,0.132584,0.132660,0.132734,0.132806,0.132877,0.132947,...,10,9,8,7,6,5,4,3,2,1
2,0.158456,0.158075,0.157637,0.157196,0.156753,0.156308,0.155861,0.155412,0.154960,0.154507,...,10,9,8,7,6,5,4,3,2,1
3,0.148230,0.148225,0.148219,0.148213,0.148207,0.148200,0.148194,0.148187,0.148181,0.148174,...,10,9,8,7,6,5,4,3,2,1
4,0.151888,0.151887,0.151886,0.151886,0.151885,0.151885,0.151884,0.151884,0.151884,0.151883,...,10,9,8,7,6,5,4,3,2,1


In [20]:
a_bdnn_tem_2_sp_rates = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/temnospondyli/mcmc_no_predictors/A_bdnn_update/temnospondyli_pyrate_2_A_update_G_BDS_BDNN_4_2Tc_sp_rates.log", sep="\t", header=0)
a_bdnn_tem_2_sp_rates.shape


(9999, 269)

In [23]:
c_bdnn_tem_2_minmax_boxcox = pd.read_csv("./temnospondyli/mcmc_fixshift_predictors/C_bdnn_minmax_boxcox/temnospondyli_pyrate_2_C_minmax_boxcox_G_BDS_BDNN_16_8TVc_mcmc.log", sep="\t", header=0)
c_bdnn_tem_2_minmax_boxcox_sp_rates = pd.read_csv("./temnospondyli/mcmc_fixshift_predictors/C_bdnn_minmax_boxcox/temnospondyli_pyrate_2_C_minmax_boxcox_G_BDS_BDNN_16_8TVc_sp_rates.log", sep="\t", header=0)
c_bdnn_tem_2_minmax_boxcox_ex_rates = pd.read_csv("./temnospondyli/mcmc_fixshift_predictors/C_bdnn_minmax_boxcox/temnospondyli_pyrate_2_C_minmax_boxcox_G_BDS_BDNN_16_8TVc_ex_rates.log", sep="\t", header=0)
c_bdnn_tem_2_minmax_boxcox_per_species_rates = pd.read_csv("./temnospondyli/mcmc_fixshift_predictors/C_bdnn_minmax_boxcox/temnospondyli_pyrate_2_C_minmax_boxcox_G_BDS_BDNN_16_8TVc_per_species_rates.log", sep="\t", header=0)
c_bdnn_tem_2_minmax_boxcox.shape, c_bdnn_tem_2_minmax_boxcox_sp_rates.shape, c_bdnn_tem_2_minmax_boxcox_ex_rates.shape, c_bdnn_tem_2_minmax_boxcox_per_species_rates.shape

((10000, 1016), (9999, 25), (9999, 25), (10000, 557))

In [26]:
d_bdnn_syn_1 = pd.read_csv("./synapsida/mcmc_fixshift_no_predictors/D_bdnn/synapsida_pyrate_1_D_G_BDS_BDNN_4_2Tc_mcmc.log", sep="\t", header=0)    
d_bdnn_syn_1_sp_rates = pd.read_csv("./synapsida/mcmc_fixshift_no_predictors/D_bdnn/synapsida_pyrate_1_D_G_BDS_BDNN_4_2Tc_sp_rates.log", sep="\t", header=0)
d_bdnn_syn_1_ex_rates = pd.read_csv("./synapsida/mcmc_fixshift_no_predictors/D_bdnn/synapsida_pyrate_1_D_G_BDS_BDNN_4_2Tc_ex_rates.log", sep="\t", header=0)
d_bdnn_syn_1_per_species_rates = pd.read_csv("./synapsida/mcmc_fixshift_no_predictors/D_bdnn/synapsida_pyrate_1_D_G_BDS_BDNN_4_2Tc_per_species_rates.log", sep="\t", header=0)
d_bdnn_syn_1.shape, d_bdnn_syn_1_sp_rates.shape, d_bdnn_syn_1_ex_rates.shape, d_bdnn_syn_1_per_species_rates.shape

((10000, 1106), (9999, 25), (9999, 25), (10000, 1051))

MCMC log: 10k rows

SP and EX Rates logs: 9,999 rows

Per species rates logs: 10k

## Test Concatenation of Old A_bdnn_rep

In [31]:
a_bdnn_rep_4_restored = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_restored_logs/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_mcmc.log", sep="\t", header=0)
a_bdnn_rep_4_sp_rates_restored = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_restored_logs/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_sp_rates.log", sep="\t", header=0)
a_bdnn_rep_4_ex_rates_restored = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_restored_logs/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_ex_rates.log", sep="\t", header=0)
a_bdnn_rep_4_per_species_rates_restored = pd.read_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_restored_logs/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_per_species_rates.log", sep="\t", header=0)

a_bdnn_rep_4_restored.shape, a_bdnn_rep_4_sp_rates_restored.shape, a_bdnn_rep_4_ex_rates_restored.shape, a_bdnn_rep_4_per_species_rates_restored.shape

((784, 1576), (783, 247), (783, 247), (784, 1521))

In [32]:
a_bdnn_rep_4.shape, a_bdnn_rep_4_sp_rates.shape, a_bdnn_rep_4_ex_rates.shape, a_bdnn_rep_4_per_species_rates.shape

((9693, 1576), (9693, 247), (9691, 247), (9694, 1521))

### Subsection: Did restoring happen properly?
Need to see if the sample values from the end of the incomplete log are the same as the beginning of the restored log


In [54]:
a_bdnn_rep_4.tail()

,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Yelaphomte_TE,Yimenosaurus_TE,Youngetta_TE,Youngina_TE,Youngosuchus_TE,Yunguisaurus_TE,Yunnanosaurus_TE,Zanclodon_TE,Zhongjiania_TE,Zupaysaurus_TE
9688,96880000,-16873.011765,-2204.183720,-10580.050164,-4088.777881,1.403068,5.499521,0.726976,1.492345,2.353923,...,50.007267,23.230115,75.504779,77.174034,71.114935,62.633373,25.332952,23.671876,79.775330,48.376042
9689,96890000,-16923.965870,-2205.168260,-10624.878495,-4093.919115,0.838532,5.544774,0.916111,0.866180,2.372705,...,49.836838,23.960823,75.504779,77.357398,71.757191,62.589716,25.919015,23.172924,79.393372,48.067383
9690,96900000,-16903.916517,-2209.302685,-10592.022443,-4102.591388,0.493189,5.917071,0.825036,1.124559,2.487070,...,49.244318,24.234575,75.359005,77.109246,71.850470,62.753121,25.161297,21.729372,79.520647,47.804225
9691,96910000,-16941.607216,-2208.858851,-10632.982869,-4099.765496,0.648000,5.068972,0.677283,1.000264,3.057662,...,48.471248,24.555236,75.401007,77.267084,71.921217,62.727861,25.680959,22.314353,79.489684,47.250885
9692,96920000,-16910.533269,-2208.742446,-10611.096431,-4090.694392,0.472960,5.242285,0.601698,1.227396,2.586450,...,49.190452,24.493400,75.320662,76.984644,71.807257,61.955532,26.076348,21.764681,79.791650,47.425473


In [55]:
a_bdnn_rep_4_restored.head()

,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Yelaphomte_TE,Yimenosaurus_TE,Youngetta_TE,Youngina_TE,Youngosuchus_TE,Yunguisaurus_TE,Yunnanosaurus_TE,Zanclodon_TE,Zhongjiania_TE,Zupaysaurus_TE
0,0,-20141.998519,-2093.486837,-10613.131565,-7435.380117,0.472960,5.242285,0.601698,1.227396,2.586450,...,49.190452,24.493400,75.320662,76.984644,71.807257,61.955532,26.076348,21.764681,79.791650,47.425473
1,10000,-16860.484370,-2216.861848,-10576.390883,-4067.231640,0.814114,5.643748,0.829966,1.189242,2.668586,...,49.624700,24.616003,75.497290,76.789170,71.864970,62.607390,25.832044,21.940032,79.302825,47.804238
2,20000,-16878.774860,-2219.173503,-10574.230495,-4085.370862,0.440358,4.962115,0.878228,0.833358,2.326634,...,50.165463,24.441031,75.198910,76.955158,71.917060,62.500850,26.068721,21.875667,79.558467,47.740483
3,30000,-16846.743368,-2211.374548,-10548.704926,-4086.663894,1.052405,5.561158,1.311179,0.988890,2.376652,...,50.319604,24.608636,75.271215,76.813962,71.534323,62.284348,25.792751,21.872965,79.766752,48.434819
4,40000,-16863.926255,-2216.477157,-10567.065938,-4080.383160,0.687975,5.113175,1.002654,1.104665,2.927199,...,50.307916,24.677145,75.410435,76.717019,71.737086,62.422148,25.533444,23.907241,79.732696,48.402831


First restored sample is a bit off, which shows up in the final concatenated trace file. Eventually converges, so may not be an issue

In [37]:
# Concatenating a_bdnn_rep_4_restored to the bottom of a_bdnn_rep_4 until the resulting dataframe is 10000 rows long
a_bdnn_rep_4_concat = pd.concat([a_bdnn_rep_4, a_bdnn_rep_4_restored], axis=0)
a_bdnn_rep_4_sp_rates_concat = pd.concat([a_bdnn_rep_4_sp_rates, a_bdnn_rep_4_sp_rates_restored], axis=0)
a_bdnn_rep_4_ex_rates_concat = pd.concat([a_bdnn_rep_4_ex_rates, a_bdnn_rep_4_ex_rates_restored], axis=0)
a_bdnn_rep_4_per_species_rates_concat = pd.concat([a_bdnn_rep_4_per_species_rates, a_bdnn_rep_4_per_species_rates_restored], axis=0)

# Checking that the concatenated dataframes are the right length
a_bdnn_rep_4_concat.shape[0] == a_bdnn_rep_4.shape[0] + a_bdnn_rep_4_restored.shape[0],
a_bdnn_rep_4_sp_rates_concat.shape[0] == a_bdnn_rep_4_sp_rates.shape[0] + a_bdnn_rep_4_sp_rates_restored.shape[0],
a_bdnn_rep_4_ex_rates_concat.shape[0] == a_bdnn_rep_4_ex_rates.shape[0] + a_bdnn_rep_4_ex_rates_restored.shape[0],
a_bdnn_rep_4_per_species_rates_concat.shape[0] == a_bdnn_rep_4_per_species_rates.shape[0] + a_bdnn_rep_4_per_species_rates_restored.shape[0]

True

In [39]:
# Making each dataframe only 10000 rows long
a_bdnn_rep_4_concat_10k = a_bdnn_rep_4_concat.iloc[0:10000, :]
a_bdnn_rep_4_sp_rates_concat_10k = a_bdnn_rep_4_sp_rates_concat.iloc[0:9999, :]
a_bdnn_rep_4_ex_rates_concat_10k = a_bdnn_rep_4_ex_rates_concat.iloc[0:9999, :]
a_bdnn_rep_4_per_species_rates_concat_10k = a_bdnn_rep_4_per_species_rates_concat.iloc[0:10000, :]

a_bdnn_rep_4_concat_10k.shape, a_bdnn_rep_4_sp_rates_concat_10k.shape, a_bdnn_rep_4_ex_rates_concat_10k.shape, a_bdnn_rep_4_per_species_rates_concat_10k.shape

((10000, 1576), (9999, 362), (9999, 362), (10000, 1521))

In [40]:
# Saving off the concatenated dataframe

a_bdnn_rep_4_concat_10k.to_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_concatenated_logs_test/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_mcmc_concat.log", sep="\t", index=False)
a_bdnn_rep_4_sp_rates_concat_10k.to_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_concatenated_logs_test/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_sp_rates_concat.log", sep="\t", index=False)
a_bdnn_rep_4_ex_rates_concat_10k.to_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_concatenated_logs_test/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_ex_rates_concat.log", sep="\t", index=False)
a_bdnn_rep_4_per_species_rates_concat_10k.to_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_concatenated_logs_test/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_per_species_rates_concat.log", sep="\t", index=False)


The above did not work, led to line space error. Let's try to figure out why.

Conclusion: the 'it' column of the restored log starts at 0 instead of picking up where the 'it' column of the incomplete original ends. So will have to re-number that.

In [42]:
a_bdnn_rep_4_concat_10k.head()

,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Yelaphomte_TE,Yimenosaurus_TE,Youngetta_TE,Youngina_TE,Youngosuchus_TE,Yunguisaurus_TE,Yunnanosaurus_TE,Zanclodon_TE,Zhongjiania_TE,Zupaysaurus_TE
0,0,-21792.450507,-2072.830274,-11981.405312,-7738.214920,0.370792,0.370792,0.370792,0.370792,0.370792,...,50.507011,24.694278,75.557608,76.458410,71.741797,62.606387,26.098589,27.724163,79.264315,48.459744
1,10000,-16936.108325,-2099.848585,-10398.689248,-4437.570492,0.890772,4.469665,1.083520,1.846385,1.679073,...,50.443396,24.128913,75.547243,76.493654,71.936053,62.592483,25.861068,28.185970,79.734681,48.324362
2,20000,-17122.174815,-2103.699668,-10554.352729,-4464.122418,1.092424,4.698900,1.071070,1.317639,2.464480,...,49.789423,24.619225,75.519925,77.323852,71.638421,61.815999,25.508753,27.605905,79.252009,48.392910
3,30000,-17205.036295,-2102.026680,-10633.429650,-4469.579966,0.554088,4.219277,1.034060,1.454299,1.587875,...,49.384910,24.256725,75.185990,77.322118,71.837601,60.737779,25.977118,27.567133,79.567767,48.476974
4,40000,-17289.416587,-2106.103265,-10701.358721,-4481.954601,0.318058,5.273625,1.014539,1.265484,1.978119,...,49.050608,24.394947,75.506677,76.571148,71.935869,61.388990,26.106446,27.605212,79.100243,48.255963


In [41]:
a_bdnn_rep_4.head()


,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Yelaphomte_TE,Yimenosaurus_TE,Youngetta_TE,Youngina_TE,Youngosuchus_TE,Yunguisaurus_TE,Yunnanosaurus_TE,Zanclodon_TE,Zhongjiania_TE,Zupaysaurus_TE
0,0,-21792.450507,-2072.830274,-11981.405312,-7738.214920,0.370792,0.370792,0.370792,0.370792,0.370792,...,50.507011,24.694278,75.557608,76.458410,71.741797,62.606387,26.098589,27.724163,79.264315,48.459744
1,10000,-16936.108325,-2099.848585,-10398.689248,-4437.570492,0.890772,4.469665,1.083520,1.846385,1.679073,...,50.443396,24.128913,75.547243,76.493654,71.936053,62.592483,25.861068,28.185970,79.734681,48.324362
2,20000,-17122.174815,-2103.699668,-10554.352729,-4464.122418,1.092424,4.698900,1.071070,1.317639,2.464480,...,49.789423,24.619225,75.519925,77.323852,71.638421,61.815999,25.508753,27.605905,79.252009,48.392910
3,30000,-17205.036295,-2102.026680,-10633.429650,-4469.579966,0.554088,4.219277,1.034060,1.454299,1.587875,...,49.384910,24.256725,75.185990,77.322118,71.837601,60.737779,25.977118,27.567133,79.567767,48.476974
4,40000,-17289.416587,-2106.103265,-10701.358721,-4481.954601,0.318058,5.273625,1.014539,1.265484,1.978119,...,49.050608,24.394947,75.506677,76.571148,71.935869,61.388990,26.106446,27.605212,79.100243,48.255963


In [44]:
a_bdnn_rep_4_concat_10k.tail()

,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Yelaphomte_TE,Yimenosaurus_TE,Youngetta_TE,Youngina_TE,Youngosuchus_TE,Yunguisaurus_TE,Yunnanosaurus_TE,Zanclodon_TE,Zhongjiania_TE,Zupaysaurus_TE
302,3020000,-16921.657596,-2212.941708,-10611.681005,-4097.034883,0.497822,4.840625,1.101690,1.257519,1.988408,...,46.698225,24.651535,75.398952,76.907922,71.790567,62.158047,25.963423,27.921939,79.181192,48.172980
303,3030000,-16960.516351,-2216.817361,-10644.479712,-4099.219279,0.969018,5.060727,0.781503,1.004417,2.630988,...,46.015014,24.482343,75.357427,76.745993,71.825180,62.716204,25.656795,29.107711,79.785563,48.426237
304,3040000,-16983.844249,-2218.085881,-10659.956734,-4105.801634,0.599207,5.575509,0.954376,0.801763,2.859823,...,47.259374,24.623445,74.959643,77.127476,71.542132,62.287262,25.793524,28.773126,79.575058,48.162697
305,3050000,-16986.858561,-2216.339671,-10675.683238,-4094.835652,0.662019,5.476546,0.812392,1.378928,1.997288,...,48.464749,24.606232,75.017156,76.828879,71.550434,62.496942,25.950819,29.023242,79.191964,48.110072
306,3060000,-16959.965016,-2216.174969,-10643.028354,-4100.761693,1.071203,5.697540,0.762019,1.222682,2.378555,...,48.264642,24.139749,75.445799,77.311655,71.795531,61.511390,25.485719,28.438259,78.386950,47.930669


In [43]:
a_bdnn_rep_4.tail()


,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Yelaphomte_TE,Yimenosaurus_TE,Youngetta_TE,Youngina_TE,Youngosuchus_TE,Yunguisaurus_TE,Yunnanosaurus_TE,Zanclodon_TE,Zhongjiania_TE,Zupaysaurus_TE
9688,96880000,-16873.011765,-2204.183720,-10580.050164,-4088.777881,1.403068,5.499521,0.726976,1.492345,2.353923,...,50.007267,23.230115,75.504779,77.174034,71.114935,62.633373,25.332952,23.671876,79.775330,48.376042
9689,96890000,-16923.965870,-2205.168260,-10624.878495,-4093.919115,0.838532,5.544774,0.916111,0.866180,2.372705,...,49.836838,23.960823,75.504779,77.357398,71.757191,62.589716,25.919015,23.172924,79.393372,48.067383
9690,96900000,-16903.916517,-2209.302685,-10592.022443,-4102.591388,0.493189,5.917071,0.825036,1.124559,2.487070,...,49.244318,24.234575,75.359005,77.109246,71.850470,62.753121,25.161297,21.729372,79.520647,47.804225
9691,96910000,-16941.607216,-2208.858851,-10632.982869,-4099.765496,0.648000,5.068972,0.677283,1.000264,3.057662,...,48.471248,24.555236,75.401007,77.267084,71.921217,62.727861,25.680959,22.314353,79.489684,47.250885
9692,96920000,-16910.533269,-2208.742446,-10611.096431,-4090.694392,0.472960,5.242285,0.601698,1.227396,2.586450,...,49.190452,24.493400,75.320662,76.984644,71.807257,61.955532,26.076348,21.764681,79.791650,47.425473


In [46]:
# Concatenating a_bdnn_rep_4_restored to the bottom of a_bdnn_rep_4 until the resulting dataframe is 10000 rows long
# Renumbering the 'it' column of a_bdnn_rep_4_restored to start at the end of a_bdnn_rep_4's 'it' column
a_bdnn_rep_4_concat_TEST = pd.concat([a_bdnn_rep_4, a_bdnn_rep_4_restored], axis=0)
a_bdnn_rep_4_concat_TEST_10k = a_bdnn_rep_4_concat_TEST.iloc[0:10000, :]
a_bdnn_rep_4_concat_TEST_10k['it'] = np.arange(0, a_bdnn_rep_4_concat_TEST_10k.shape[0] * 10000, 10000)
a_bdnn_rep_4_concat_TEST_10k.tail()

# a_bdnn_rep_4_concat_TEST = pd.concat([a_bdnn_rep_4, a_bdnn_rep_4_restored], axis=0)
# a_bdnn_rep_4_concat_10k_TEST = a_bdnn_rep_4_concat.iloc[0:10000, :]



C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_24176\690849324.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a_bdnn_rep_4_concat_TEST_10k['it'] = np.arange(0, a_bdnn_rep_4_concat_TEST_10k.shape[0] * 10000, 10000)


,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Yelaphomte_TE,Yimenosaurus_TE,Youngetta_TE,Youngina_TE,Youngosuchus_TE,Yunguisaurus_TE,Yunnanosaurus_TE,Zanclodon_TE,Zhongjiania_TE,Zupaysaurus_TE
302,99950000,-16921.657596,-2212.941708,-10611.681005,-4097.034883,0.497822,4.840625,1.101690,1.257519,1.988408,...,46.698225,24.651535,75.398952,76.907922,71.790567,62.158047,25.963423,27.921939,79.181192,48.172980
303,99960000,-16960.516351,-2216.817361,-10644.479712,-4099.219279,0.969018,5.060727,0.781503,1.004417,2.630988,...,46.015014,24.482343,75.357427,76.745993,71.825180,62.716204,25.656795,29.107711,79.785563,48.426237
304,99970000,-16983.844249,-2218.085881,-10659.956734,-4105.801634,0.599207,5.575509,0.954376,0.801763,2.859823,...,47.259374,24.623445,74.959643,77.127476,71.542132,62.287262,25.793524,28.773126,79.575058,48.162697
305,99980000,-16986.858561,-2216.339671,-10675.683238,-4094.835652,0.662019,5.476546,0.812392,1.378928,1.997288,...,48.464749,24.606232,75.017156,76.828879,71.550434,62.496942,25.950819,29.023242,79.191964,48.110072
306,99990000,-16959.965016,-2216.174969,-10643.028354,-4100.761693,1.071203,5.697540,0.762019,1.222682,2.378555,...,48.264642,24.139749,75.445799,77.311655,71.795531,61.511390,25.485719,28.438259,78.386950,47.930669


In [47]:
a_bdnn_rep_4_concat_TEST_10k.to_csv("C:/Users/SimoesLabAdmin/Documents/BDNN_Arielli/reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_concatenated_logs_test/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_mcmc_concat_TEST.log", sep="\t", index=False)

In [48]:
# Compare to a complete mcmc log to make sure the 'it' column is correct
a_bdnn_tem_1.tail()

,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Watsonisuchus_Antarctic_TE,Watsonisuchus_Temperate_S_TE,Wellesaurus_TE,Wetlugasaurus_TE,Xenobrachyops_TE,Xenotosuchus_TE,Yarengia_TE,Yuanansuchus_TE,Zatrachys_TE,Zygosaurus_TE
9995,99950000,-9888.607243,-2332.007269,-5895.517826,-1661.082149,7.678395,2.178331,1.151020,0.301625,0.396735,...,73.822584,72.187940,72.350408,72.162358,76.416260,66.340428,71.120738,68.522670,103.438891,88.614647
9996,99960000,-9860.394410,-2334.700982,-5864.541121,-1661.152307,8.259268,2.402046,1.683230,0.415987,0.584225,...,74.377345,73.099666,71.761588,72.302592,76.349113,67.074361,70.940757,67.494991,102.821858,86.323150
9997,99970000,-9877.758572,-2331.727786,-5876.911711,-1669.119076,7.946897,2.396659,1.431586,0.352037,0.453839,...,74.000801,72.534754,70.965357,72.192118,76.427298,65.319626,72.094847,67.832615,102.401496,86.417578
9998,99980000,-9894.315023,-2331.766373,-5892.731793,-1669.816856,7.199144,2.329524,1.343906,0.314652,0.307420,...,74.612472,73.111750,70.667992,72.311783,76.430729,66.663474,70.613733,68.739662,102.740552,85.551134
9999,99990000,-9924.795594,-2334.312907,-5923.961694,-1666.520993,7.130627,2.558124,1.484601,0.294063,0.393100,...,72.529533,72.897259,71.252363,70.568735,76.434458,66.911609,71.617010,68.739665,102.595936,86.463639


In [49]:
c_bdnn_tem_2_minmax_boxcox.tail()

,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Watsonisuchus_Antarctic_TE,Watsonisuchus_Temperate_S_TE,Wellesaurus_TE,Wetlugasaurus_TE,Xenobrachyops_TE,Xenotosuchus_TE,Yarengia_TE,Yuanansuchus_TE,Zatrachys_TE,Zygosaurus_TE
9995,99950000,-8037.830206,-823.403346,-5824.489212,-1389.937647,7.619389,2.426511,1.576404,0.322179,0.229892,...,76.345632,72.052681,72.490416,71.900733,76.526344,66.734478,67.613210,69.116827,97.618003,81.039364
9996,99960000,-8093.938365,-822.077557,-5863.828262,-1408.032546,7.434710,1.906747,1.394825,0.304986,0.318550,...,76.448543,72.356251,72.877102,72.097531,76.448884,65.592928,67.911986,69.088728,101.397014,81.590997
9997,99970000,-8107.008449,-812.049781,-5895.911198,-1399.047470,7.304078,1.859900,1.499098,0.290279,0.318667,...,76.447732,72.326662,72.852349,71.848244,76.494068,67.278240,68.654658,68.505431,102.226540,82.794209
9998,99980000,-8073.436051,-808.507582,-5863.909090,-1401.019379,8.169915,2.126098,1.517327,0.203840,0.248170,...,76.237694,72.275001,72.633568,71.377391,76.450761,66.992739,67.502553,69.018377,101.251423,81.040073
9999,99990000,-8042.678457,-808.327720,-5849.784051,-1384.566686,7.684239,2.230272,1.525918,0.305262,0.248190,...,76.355549,72.276166,71.236717,71.517060,76.516646,66.782961,68.462421,68.377881,101.571125,81.317431


# Making a Function

In [2]:
# INITIAL DRAFT FUNCTION FOR JUST MCMC LOG
# Read in an incomplete log file
# Read in a restored log file
# Concatenate the two log files
# Check that the concatenated log file is the right length 
# by comparing its shape[0] with the sum of the shape[0]'s of the original and restored log files to the concatenated log file
# Cutting the concatenated log file to 10000 rows
# Renumbering the 'it' column from 0 with step sizes of 10000
# Check that the last value in the 'it' column is 99990000
# Return the resulting dataframe only if all the checks are correct
# return an error message if any of the checks are incorrect, specifying which check was failed
# Save the resulting dataframe as a log file

# def concatenate_logs(original_log, restored_log, output_log):
#     original = pd.read_csv(original_log, sep="\t", header=0)
#     restored = pd.read_csv(restored_log, sep="\t", header=0)
#     concatenated = pd.concat([original, restored], axis=0)
#     if concatenated.shape[0] == original.shape[0] + restored.shape[0]:
#         concatenated_10k = concatenated.iloc[0:10000, :]
#         concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)
#         concatenated_10k.to_csv(output_log, sep="\t", index=False)
#         # print out the number of rows in the original, the restored, the concatenated, and the concatenated_10k
#         print(f"Original: {original.shape[0]} rows", f"Restored: {restored.shape[0]} rows", 
#               f"Concatenated: {concatenated.shape[0]} rows", f"Concatenated_10k: {concatenated_10k.shape[0]} rows")
#         return concatenated_10k
#     else:
#         return "The concatenated log file is the wrong length"
    

In [4]:
# # SECOND DRAFT W/ HARDCODED 10K ROWS FOR FINAL CONCAT LOG (WORKS)
# # CREATING A CUSTOM FUNCTION TO CONCATENATE ALL LOG FILES
# # Same function/workflow as the concatenate_logs function above, but now include the ex_rates, sp_rates, and per_species_rates log files in addition to the mcmc log file
# # these files should be named with the same prefix as the mcmc log file, but with the suffixes "_sp_rates", "_ex_rates", and "_per_species_rates"
# # Save the resulting dataframes as log files to the same directory as the mcmc log file, but with the same prefix as the mcmc log file, and the suffixes "_sp_rates", "_ex_rates", and "_per_species_rates"

# import pandas as pd
# import numpy as np
# import os

# def concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix):
#     suffixes = ['_mcmc.log', '_ex_rates.log', '_sp_rates.log', '_per_species_rates.log']
    
#     def process_log_files(original_log_prefix, restored_log_prefix, suffix):
#         original_log = original_log_prefix + suffix
#         restored_log = restored_log_prefix + suffix
#         output_log = output_log_prefix + suffix.replace('.log', '_CONCAT.log')

#         # Need to add a "does this file exist" check, b/c  only BDNN runs have the "per_species_rates.log", and I want this function to work on
#         # all runs, not just BDNN runs
#         if not os.path.exists(original_log) or not os.path.exists(restored_log):
#             print(f"Skipping {suffix} because the file does not exist.")
#             return None
        
#         # Need to add these try and except blocks because RJMCMC sp_rates and ex_rates.logs will have a different number of columns in each row!
#         # Which would lead to a parse error when reading in the log file
#         try:
#             original = pd.read_csv(original_log, sep="\t", header=0)
#         except pd.errors.ParserError as e:
#             print(f"Skipping {suffix} because of a parsing error in the original log file: {e}")
#             return None
        
#         try:
#             restored = pd.read_csv(restored_log, sep="\t", header=0)
#         except pd.errors.ParserError as e:
#             print(f"Skipping {suffix} because of a parsing error in the restored log file: {e}")
#             return None
      
#         # Drop the very first row in the restored log b/c PyRate had an old issue where the first row was restored improperly
#         # This issue has been fixed in the current version of PyRate, but the restored logs from the old version still have this issue
#         restored = restored.iloc[1:, :]
#         concatenated = pd.concat([original, restored], axis=0)
        
#         if concatenated.shape[0] == original.shape[0] + restored.shape[0]:
#             concatenated_10k = concatenated.iloc[0:10000, :]
            
#             if suffix == '_mcmc.log':
#                 concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)
#                 if concatenated_10k['it'].iloc[-1] != 99990000:
#                     raise ValueError(f"The last value in the 'it' column is not 99990000 for {suffix} logs.")
#             elif suffix == '_per_species_rates.log':
#                 concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)
#                 if concatenated_10k['iterations'].iloc[-1] != 99990000:
#                     raise ValueError(f"The last value in the 'iterations' column is not 99990000 for {suffix} logs.")
            
#             concatenated_10k.to_csv(output_log, sep="\t", index=False)
#             print(f"Original ({suffix}): {original.shape[0]} rows", 
#                   f"Restored ({suffix}): {restored.shape[0]} rows", 
#                   f"Concatenated ({suffix}): {concatenated.shape[0]} rows", 
#                   f"Concatenated_10k ({suffix}): {concatenated_10k.shape[0]} rows")
#             return concatenated_10k
#         else:
#             raise ValueError(f"The concatenated log file is the wrong length for {suffix} logs.")
    
#     results = {}
#     for suffix in suffixes:
#         result = process_log_files(original_log_prefix, restored_log_prefix, suffix)
#         if result is not None: # Results would be none if the file didn't exist (if non-BDNN, with no _per_species_rates.log)
#             results[suffix] = result
#     return results


# # Example Usage:
# # Suppose you have the following log files:

# # Original log files:
# # ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_mcmc.log
# # ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_ex_rates.log
# # ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_sp_rates.log
# # ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_per_species_rates.log
# # Restored log files with the same names but in a different directory.
# # You would call the function as follows:

# # original_log_prefix = './reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc'
# # restored_log_prefix = './restored_logs/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc'
# # restored_log_prefix = './restored_logs/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc'

# # results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
# # This function will concatenate and process all the specified log files, save the resulting dataframes with the suffix _FINAL.log, 
#  # and print out the relevant information for each log file. If any check fails, it will raise an error specifying which check failed.

In [ ]:
# # FUNCTION VERSION WITH NUM_ROWS ARGUMENT CHOSEN BY THE USER
# # CREATING A CUSTOM FUNCTION TO CONCATENATE ALL LOG FILES
# # Same function/workflow as the concatenate_logs function above, but now include the ex_rates, sp_rates, and per_species_rates log files in addition to the mcmc log file
# # these files should be named with the same prefix as the mcmc log file, but with the suffixes "_sp_rates", "_ex_rates", and "_per_species_rates"
# # Save the resulting dataframes as log files to the same directory as the mcmc log file, but with the same prefix as the mcmc log file, and the suffixes "_sp_rates", "_ex_rates", and "_per_species_rates"

# import pandas as pd
# import numpy as np
# import os

# def concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix, num_rows):
#     suffixes = ['_mcmc.log', '_ex_rates.log', '_sp_rates.log', '_per_species_rates.log', '_marginal_rates.log']
    
#     def process_log_files(original_log_prefix, restored_log_prefix, suffix):
#         original_log = original_log_prefix + suffix
#         restored_log = restored_log_prefix + suffix
#         output_log = output_log_prefix + '_CONCAT' + suffix

#         # Check if the files exist
#         if not os.path.exists(original_log) or not os.path.exists(restored_log):
#             print(f"Skipping {suffix} because the file does not exist")
#             return None
        
#         # Try reading the log files, handling parsing errors
#         try:
#             original = pd.read_csv(original_log, sep="\t", header=0)
#         except pd.errors.ParserError as e:
#             print(f"Skipping {suffix}")
#             return None
        
#         try:
#             restored = pd.read_csv(restored_log, sep="\t", header=0)
#         except pd.errors.ParserError as e:
#             print(f"Skipping {suffix} because of a parsing error in the restored log file: {e}. The log file may have rows with differing #'s of columns")
#             return None
      
#         # Drop the very first row in the restored log
#         restored = restored.iloc[1:, :]
#         concatenated = pd.concat([original, restored], axis=0)
        
#         if concatenated.shape[0] == original.shape[0] + restored.shape[0]:
#             concatenated_final = concatenated.iloc[:num_rows, :]
            
#             if suffix == '_mcmc.log':
#                 concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)
#                 if concatenated_final['it'].iloc[-1] != (num_rows - 1) * 10000:
#                     raise ValueError(f"The last value in the 'it' column is not {(num_rows - 1) * 10000} for {suffix} logs.")
#             elif suffix == '_per_species_rates.log':
#                 concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)
#                 if concatenated_final['iterations'].iloc[-1] != (num_rows - 1) * 10000:
#                     raise ValueError(f"The last value in the 'iterations' column is not {(num_rows - 1) * 10000} for {suffix} logs.")
#             elif suffix == '_marginal_rates.log':
#                 concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)
#                 if concatenated_final['iterations'].iloc[-1] != (num_rows - 1) * 10000:
#                     raise ValueError(f"The last value in the 'iterations' column is not {(num_rows - 1) * 10000} for {suffix} logs.")
            
#             concatenated_final.to_csv(output_log, sep="\t", index=False)
#             print(f"Original ({suffix}): {original.shape[0]} rows", 
#                   f"Restored ({suffix}): {restored.shape[0]} rows", 
#                   f"Concatenated ({suffix}): {concatenated.shape[0]} rows", 
#                   f"Concatenated_final ({suffix}): {concatenated_final.shape[0]} rows")
#             return concatenated_final
#         else:
#             raise ValueError(f"The concatenated log file is the wrong length for {suffix} logs.")
    
#     results = {}
#     for suffix in suffixes:
#         result = process_log_files(original_log_prefix, restored_log_prefix, suffix)
#         if result is not None: # Results would be none if the file didn't exist (if non-BDNN, with no _per_species_rates.log)
#             results[suffix] = result
#     return results


# # Example Usage:
# # Suppose you have the following log files:

# # Original log files:
# # ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_mcmc.log
# # ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_ex_rates.log
# # ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_sp_rates.log
# # ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_per_species_rates.log
# # Restored log files with the same names but in a different directory.
# # You would call the function as follows:

# # original_log_prefix = './reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc'
# # restored_log_prefix = './restored_logs/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc'
# # output_log_prefix = './output_logs/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc'
# # num_rows = 10000

# # results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix, num_rows)
# # This function will concatenate and process all the specified log files, save the resulting dataframes with the suffix _CONCAT.log, 
# # and print out the relevant information for each log file. If any check fails, it will raise an error specifying which check failed.

Final function: concatenated log file should use all available rows in the original and restored, so that each replicate has the same number of columns in each log file, compared to other replicates, but some replicates might have more/less rows in each log file compared to other replicates. Here's the convo I had with Tiago about this reasoning:

**Me**:
I've had to restore some mcmc runs that didn't reach 100 million iterations, and in the process the final concatenated files end up having 100+ million iterations (varies, some are 150, some are 110, etc.). I can definitely cut the final concatenated logs to 100 million iterations across the board, but I also wanted to use all the data we have. So:
1. Do we want every run on every model w/ every replicate to have the same number of MCMC iterations/samples, in order to maintain consistency across the board as we compare results?
2. OR do we want to preserve the maximum number of MCMC iterations/samples available for each run, which means various models would have more samples than other models?


**Tiago**: 
The answer to your question is option number two. It doesn't really matter for all analyses to have the exact same number of generations. The goal is for us to have the posterior being sampled from a stationarity phase (some models will always take longer to get there relative to others, even if they have the same total number of generations). So in a sense, the total number of generations doesn't really matter... What matters is where your sampling is coming from. Also, all your parameter estimates will come from the parts of the posterior actually being sampled (e.g., if the sample at every 1000 generations, that means you will have 10,000 samples when running for 100 million generations). But you can always filter down your posterior to have exactly 10,000 samples across all model iterations no matter the total number of generations. In a sense, your total sample size matters much more than the total number of generations used.

**Note**: Note that the unnamed/empty header column ("") in the original marginal_rates.log is default renamed by Python to "Unnamed: 898". When I -combLogRJ (combine replicates' logs) with concatentaed marginal_rates.log files (have the "Unnamed: 898" column) and original marginal_rates.log files (have the unnamed/empty header column ""), this does not pose an issue. All that matters is that the files have the same # of columns


In [115]:
# New function, response to the email above^

import pandas as pd
import numpy as np
import os

def concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix):
    suffixes = ['_mcmc.log', '_ex_rates.log', '_sp_rates.log', '_per_species_rates.log', '_marginal_rates.log']
    
    def process_log_files(original_log_prefix, restored_log_prefix, suffix):
        original_log = original_log_prefix + suffix
        restored_log = restored_log_prefix + suffix
        output_log = output_log_prefix + '_CONCAT' + suffix

        # Check if the files exist
        if not os.path.exists(original_log) or not os.path.exists(restored_log):
            print(f"Skipping {suffix} because the file does not exist in the specified directory. Check path.")
            return None
        
        # Try reading the log files, handling parsing errors
        try:
            original = pd.read_csv(original_log, sep="\t", header=0)
        except pd.errors.ParserError as e:
            print(f"Skipping {suffix} because of a parsing error in the original log file: {e}. The log file may have rows with differing #'s of columns")
            return None
        
        try:
            restored = pd.read_csv(restored_log, sep="\t", header=0)
        except pd.errors.ParserError as e:
            print(f"Skipping {suffix} because of a parsing error in the restored log file: {e}. The log file may have rows with differing #'s of columns")
            return None
        
        # Strip any trailing or leading whitespace from the col names, so that no duplicate cols are created mistakenly 
        # If restored log has " 0.72" as a header, but original has "0.72", then a duplicate column will be created
        # This has only proven itself an issue with the _per_species_rates.log file, but it is good practice to do this for all log files
        original.columns = original.columns.str.strip()
        restored.columns = restored.columns.str.strip()
      
        # Drop the very first row in the restored log
        restored = restored.iloc[1:, :]
        concatenated = pd.concat([original, restored], axis=0)
        
        if concatenated.shape[0] == original.shape[0] + restored.shape[0]:
            # Keep all rows from the concatenated dataframe
            concatenated_final = concatenated
            
            # Update iteration columns based on the log type
            if suffix == '_mcmc.log':
                concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)
                if concatenated_final['it'].iloc[-1] != (concatenated_final.shape[0] - 1) * 10000:
                    raise ValueError(f"The last value in the 'it' column is not {(concatenated_final.shape[0] - 1) * 10000} for {suffix} logs.")
            elif suffix in ['_marginal_rates.log']:
                concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)
                if concatenated_final['it'].iloc[-1] != (concatenated_final.shape[0] - 1) * 10000:
                    raise ValueError(f"The last value in the 'it' column is not {(concatenated_final.shape[0] - 1) * 10000} for {suffix} logs.")
            
            concatenated_final.to_csv(output_log, sep="\t", index=False)
            print(f"\n Original ({suffix}): {original.shape[0]} rows, {original.shape[1]} columns \n",
                  f"Restored ({suffix}): {restored.shape[0]} rows, {restored.shape[1]} columns \n", 
                  f"Concatenated ({suffix}): {concatenated_final.shape[0]} rows, {concatenated_final.shape[1]} columns \n",)
            return concatenated_final
        else:
            raise ValueError(f"The concatenated log file is the wrong length for {suffix} logs.")
    
    results = {}
    for suffix in suffixes:
        result = process_log_files(original_log_prefix, restored_log_prefix, suffix)
        if result is not None: # Results would be none if the file didn't exist (if non-BDNN, with no _per_species_rates.log)
            results[suffix] = result
    return results


# Example Usage:
# Suppose you have the following log files:

# Original log files:
# ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_mcmc.log
# ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_ex_rates.log
# ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_sp_rates.log
# ./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc_per_species_rates.log
# Restored log files with the same names but in a different directory.
# You would call the function as follows:

# original_log_prefix = './reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc'
# restored_log_prefix = './restored_logs/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc'
# output_log_prefix = './output_logs/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc'

# results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
# This function will concatenate and process all the specified log files, save the resulting dataframes with the suffix _CONCAT.log, 
# and print out the relevant information for each log file. If any check fails, it will raise an error specifying which check failed.

Tests below are all of a previous version that hardcoded in 10k rows for the final concatenated log. That version is commented out in a cell above the current version, which takes "num_rows" as an argument so that the user can set the final number of rows in the concatenated log

This is helpful because sometimes I have much more than 10k samples in my mcmc logs, and I don't want to not use data if I have it

In [ ]:
concatenate_logs("./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc", 
                           "./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_restored_logs/reptilia_pyrate_5_A_G_BDS_BDNN_4_2Tc",
                           "./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_concatenated_logs_test/reptilia_pyrate_5_G_BDS_BDNN_4_2Tc")


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_24176\688856887.py:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 9807 rows Restored (_mcmc.log): 194 rows Concatenated (_mcmc.log): 10001 rows Concatenated_10k (_mcmc.log): 10000 rows
Original (_ex_rates.log): 9806 rows Restored (_ex_rates.log): 193 rows Concatenated (_ex_rates.log): 9999 rows Concatenated_10k (_ex_rates.log): 9999 rows
Original (_sp_rates.log): 9806 rows Restored (_sp_rates.log): 193 rows Concatenated (_sp_rates.log): 9999 rows Concatenated_10k (_sp_rates.log): 9999 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_24176\688856887.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 9807 rows Restored (_per_species_rates.log): 194 rows Concatenated (_per_species_rates.log): 10001 rows Concatenated_10k (_per_species_rates.log): 10000 rows


{'_mcmc.log':            it     posterior        prior        PP_lik       BD_lik       q_0  \
 0           0 -20803.553606 -2074.971021 -11046.839006 -7681.743580  0.763968   
 1       10000 -16852.722912 -2093.977239 -10335.389099 -4423.356574  0.620370   
 2       20000 -16984.991160 -2098.046076 -10454.860419 -4432.084665  0.440224   
 3       30000 -17116.775171 -2098.870829 -10570.101632 -4447.802711  0.440504   
 4       40000 -17164.937090 -2098.991856 -10612.587083 -4453.358151  0.546420   
 ..        ...           ...          ...           ...          ...       ...   
 188  99950000 -16890.540669 -2201.445131 -10594.263558 -4094.831979  0.805668   
 189  99960000 -16868.136355 -2207.279190 -10577.230441 -4083.626723  0.355412   
 190  99970000 -16904.632055 -2202.341682 -10609.944236 -4092.346137  0.434446   
 191  99980000 -16906.705917 -2200.708724 -10612.624136 -4093.373057  0.630511   
 192  99990000 -16910.855289 -2199.671450 -10608.541910 -4102.641929  0.616097   
 
 

The final concatenated trace file that results from that function ('./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_concatenated_logs/reptilia_pyrate_5_A_G_BDS_BDNN_4_2Tc_mcmc_final_concat.log') has a big dip at the concatenation point, which means at that point there is a sample that is very off. Go to Section of the notebook: "Subsection: Did restoring happen properly?"

In [56]:
# More tests
concatenate_logs("./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_6_G_BDS_BDNN_4_2Tc_mcmc.log", 
                           "./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_restored_logs/reptilia_pyrate_6_A_G_BDS_BDNN_4_2Tc_mcmc.log", 
                           './reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_concatenated_logs/reptilia_pyrate_6_A_G_BDS_BDNN_4_2Tc_mcmc_final_concat.log')



C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_24176\2413614197.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original: 9955 rows Restored: 46 rows Concatenated: 10001 rows Concatenated_10k: 10000 rows


,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Yelaphomte_TE,Yimenosaurus_TE,Youngetta_TE,Youngina_TE,Youngosuchus_TE,Yunguisaurus_TE,Yunnanosaurus_TE,Zanclodon_TE,Zhongjiania_TE,Zupaysaurus_TE
0,0,-20704.500451,-2075.561783,-10939.216289,-7689.722379,0.961239,0.961239,0.961239,0.961239,0.961239,...,48.842529,24.684535,72.361893,76.894563,70.039762,61.855868,25.843654,24.746318,78.286066,44.722017
1,10000,-16955.353188,-2100.943720,-10419.055024,-4435.354444,0.614594,4.300142,1.095018,1.125870,4.846087,...,48.629226,24.560153,72.362953,76.498824,69.979914,61.587707,25.785049,25.961522,77.917042,44.216192
2,20000,-17058.907568,-2104.100138,-10511.690367,-4443.117062,0.503999,4.683602,0.485053,0.764259,5.668789,...,48.880574,24.663633,72.389923,76.587198,69.972800,61.815981,25.550892,25.823780,78.635247,44.711152
3,30000,-17071.201250,-2102.985928,-10526.607567,-4441.607755,0.358449,4.398529,0.852979,0.834338,4.969660,...,48.802106,24.498932,72.078687,76.928052,70.083508,62.206860,25.385549,26.251067,79.121252,44.613930
4,40000,-17246.827539,-2105.236725,-10683.458051,-4458.132764,0.334761,4.996461,1.050775,0.658815,4.976742,...,48.552445,24.106181,72.412550,76.874849,69.725176,61.290949,24.555377,26.165450,79.086383,44.107758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,99950000,-17061.207871,-2212.419142,-10745.533222,-4103.255507,0.815808,4.571029,0.933591,0.648660,5.183557,...,48.366921,24.645406,72.338634,77.128431,69.656932,61.323303,24.838485,30.069499,79.265711,44.383952
41,99960000,-17007.579825,-2210.867088,-10687.737341,-4108.975396,0.395347,4.727469,0.777131,0.398958,5.347324,...,47.830875,24.587682,72.405725,77.215778,69.958718,61.101626,25.597133,28.924204,79.247944,44.594345
42,99970000,-16933.042729,-2212.462635,-10626.983275,-4093.596819,0.422879,4.227472,0.828863,0.611324,4.788692,...,47.971044,24.433402,71.279006,75.862599,69.419473,60.585888,25.625431,28.515608,78.638095,44.614776
43,99980000,-16923.801236,-2209.414483,-10611.181272,-4103.205481,0.698841,4.610498,0.857681,0.654349,5.345159,...,48.647252,24.418772,71.639799,76.372817,70.016003,60.881407,25.848045,28.298666,78.731333,44.674685


In [57]:
# More tests
concatenate_logs("./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_7_G_BDS_BDNN_4_2Tc_mcmc.log", 
                           "./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_restored_logs/reptilia_pyrate_7_A_G_BDS_BDNN_4_2Tc_mcmc.log", 
                           './reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_concatenated_logs/reptilia_pyrate_7_A_G_BDS_BDNN_4_2Tc_mcmc_final_concat.log')



C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_24176\2413614197.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original: 9607 rows Restored: 394 rows Concatenated: 10001 rows Concatenated_10k: 10000 rows


,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Yelaphomte_TE,Yimenosaurus_TE,Youngetta_TE,Youngina_TE,Youngosuchus_TE,Yunguisaurus_TE,Yunnanosaurus_TE,Zanclodon_TE,Zhongjiania_TE,Zupaysaurus_TE
0,0,-21297.054764,-2151.277849,-11448.080279,-7697.696635,0.535589,0.535589,0.535589,0.535589,0.535589,...,36.004642,24.803292,75.286424,77.366286,71.475584,58.821141,24.037330,12.947814,79.995310,34.075403
1,10000,-17028.478619,-2171.520780,-10421.351695,-4435.606144,0.680679,3.694337,0.932558,0.945219,1.614736,...,35.890017,24.690509,75.397299,77.278466,71.385988,58.374042,24.232853,13.271493,80.271664,34.101106
2,20000,-17154.992603,-2167.684885,-10532.472925,-4454.834793,0.436856,3.571272,0.681865,1.034551,1.742773,...,35.899201,24.563214,75.359960,77.291819,70.827869,57.948477,24.289547,14.685136,79.365336,34.074358
3,30000,-17151.645813,-2165.941219,-10532.790045,-4452.914550,0.591307,4.541130,0.941140,1.080777,1.832091,...,36.007358,24.857115,75.430495,77.157302,71.515364,57.493311,24.127489,14.256306,79.321875,34.131724
4,40000,-17203.792941,-2167.868761,-10584.084329,-4451.839851,0.469032,4.931942,0.957374,0.727884,1.495301,...,35.527740,24.707637,75.412601,76.998066,71.445040,57.242781,24.034499,13.661398,80.019068,34.126315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,99950000,-16928.404958,-2207.685408,-10627.796000,-4092.923550,0.265033,5.207407,0.774699,2.057921,2.344593,...,35.897153,24.937958,74.813852,77.306368,71.322192,61.764689,24.022294,30.098326,79.156424,33.813293
389,99960000,-16853.230177,-2212.572593,-10565.763262,-4074.894322,0.638029,5.543422,0.861810,2.594027,2.176134,...,33.426147,24.949318,74.993486,77.103244,71.195213,61.402065,22.900699,28.425133,79.690077,34.041013
390,99970000,-16835.769593,-2205.748314,-10554.356973,-4075.664306,0.545219,5.291758,0.699199,1.617182,2.995361,...,32.052162,24.836792,75.429407,77.155500,71.400748,60.963664,23.802493,28.758060,80.716964,33.602059
391,99980000,-16841.247715,-2201.309322,-10560.278917,-4079.659476,0.602072,5.208284,0.805001,1.500709,2.771585,...,31.921426,24.178708,74.990583,77.311133,71.306159,61.410679,24.403431,29.742547,80.787986,33.855932


# Loop for Applying Function

In [8]:
# Loop for applying the concatenate_logs function to all replicates in a directory. 
# Use the "range" portion to specify which replicates need concatenating

for i in range(4,8):
    original_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_original_incomplete_logs/reptilia_pyrate_{i}_G_BDS_BDNN_4_2Tc"
    restored_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_restored_logs/reptilia_pyrate_{i}_A_G_BDS_BDNN_4_2Tc"
    output_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_concatenated_logs/reptilia_pyrate_{i}_A_G_BDS_BDNN_4_2Tc"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix, 10000)
    print(f"Finished processing reptilia_pyrate_{i}")

C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 9693 rows Restored (_mcmc.log): 783 rows Concatenated (_mcmc.log): 10476 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 9691 rows Restored (_ex_rates.log): 782 rows Concatenated (_ex_rates.log): 10473 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 9693 rows Restored (_sp_rates.log): 782 rows Concatenated (_sp_rates.log): 10475 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 9694 rows Restored (_per_species_rates.log): 783 rows Concatenated (_per_species_rates.log): 10477 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing reptilia_pyrate_4
Original (_mcmc.log): 9807 rows Restored (_mcmc.log): 193 rows Concatenated (_mcmc.log): 10000 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 9806 rows Restored (_ex_rates.log): 192 rows Concatenated (_ex_rates.log): 9998 rows Concatenated_final (_ex_rates.log): 9998 rows
Original (_sp_rates.log): 9806 rows Restored (_sp_rates.log): 192 rows Concatenated (_sp_rates.log): 9998 rows Concatenated_final (_sp_rates.log): 9998 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 9807 rows Restored (_per_species_rates.log): 193 rows Concatenated (_per_species_rates.log): 10000 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing reptilia_pyrate_5
Original (_mcmc.log): 9955 rows Restored (_mcmc.log): 45 rows Concatenated (_mcmc.log): 10000 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 9953 rows Restored (_ex_rates.log): 44 rows Concatenated (_ex_rates.log): 9997 rows Concatenated_final (_ex_rates.log): 9997 rows
Original (_sp_rates.log): 9954 rows Restored (_sp_rates.log): 44 rows Concatenated (_sp_rates.log): 9998 rows Concatenated_final (_sp_rates.log): 9998 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 9955 rows Restored (_per_species_rates.log): 45 rows Concatenated (_per_species_rates.log): 10000 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing reptilia_pyrate_6
Original (_mcmc.log): 9607 rows Restored (_mcmc.log): 393 rows Concatenated (_mcmc.log): 10000 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 9606 rows Restored (_ex_rates.log): 392 rows Concatenated (_ex_rates.log): 9998 rows Concatenated_final (_ex_rates.log): 9998 rows
Original (_sp_rates.log): 9606 rows Restored (_sp_rates.log): 392 rows Concatenated (_sp_rates.log): 9998 rows Concatenated_final (_sp_rates.log): 9998 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 9607 rows Restored (_per_species_rates.log): 393 rows Concatenated (_per_species_rates.log): 10000 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing reptilia_pyrate_7


## A) mcmc_no_predictors

### Reptilia

In [117]:
# A_bdnn
for i in range(4,8):
    original_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_original_incomplete_logs/reptilia_pyrate_{i}_G_BDS_BDNN_4_2Tc"
    restored_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_restored_logs/reptilia_pyrate_{i}_A_G_BDS_BDNN_4_2Tc"
    output_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_{i}_A_G_BDS_BDNN_4_2Tc"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
    print(f"Finished processing reptilia_pyrate_{i}")


 Original (_mcmc.log): 9693 rows, 1576 columns 
 Restored (_mcmc.log): 783 rows, 1576 columns 
 Concatenated (_mcmc.log): 10476 rows, 1576 columns 


 Original (_ex_rates.log): 9691 rows, 247 columns 
 Restored (_ex_rates.log): 782 rows, 247 columns 
 Concatenated (_ex_rates.log): 10473 rows, 362 columns 


 Original (_sp_rates.log): 9693 rows, 247 columns 
 Restored (_sp_rates.log): 782 rows, 247 columns 
 Concatenated (_sp_rates.log): 10475 rows, 362 columns 


 Original (_per_species_rates.log): 9694 rows, 1521 columns 
 Restored (_per_species_rates.log): 783 rows, 1521 columns 
 Concatenated (_per_species_rates.log): 10477 rows, 1521 columns 

Skipping _marginal_rates.log because the file does not exist in the specified directory. Check path.
Finished processing reptilia_pyrate_4

 Original (_mcmc.log): 9807 rows, 1576 columns 
 Restored (_mcmc.log): 193 rows, 1576 columns 
 Concatenated (_mcmc.log): 10000 rows, 1576 columns 


 Original (_ex_rates.log): 9806 rows, 247 columns 
 R

In [64]:
# A_bdnn_update
for i in range(1,11):
    original_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdnn_update/reptilia_pyrate_{i}_A_update_G_BDS_BDNN_4_2Tc"
    restored_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdnn_update/A_bdnn_update_restored_logs/reptilia_pyrate_{i}_A_update_restored_G_BDS_BDNN_4_2Tc"
    output_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdnn_update/reptilia_pyrate_{i}_A_G_BDS_BDNN_4_2Tc"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
    print(f"Finished processing reptilia_pyrate_{i}")

Original (_mcmc.log): 7092 rows Restored (_mcmc.log): 9090 rows Concatenated (_mcmc.log): 16182 rows
Original (_ex_rates.log): 7091 rows Restored (_ex_rates.log): 9089 rows Concatenated (_ex_rates.log): 16180 rows
Original (_sp_rates.log): 7091 rows Restored (_sp_rates.log): 9089 rows Concatenated (_sp_rates.log): 16180 rows
Original (_per_species_rates.log): 7092 rows Restored (_per_species_rates.log): 9090 rows Concatenated (_per_species_rates.log): 16182 rows
Skipping _marginal_rates.log because the file does not exist in the specified directory. Check path.
Finished processing reptilia_pyrate_1
Original (_mcmc.log): 7300 rows Restored (_mcmc.log): 9406 rows Concatenated (_mcmc.log): 16706 rows
Original (_ex_rates.log): 7299 rows Restored (_ex_rates.log): 9405 rows Concatenated (_ex_rates.log): 16704 rows
Original (_sp_rates.log): 7299 rows Restored (_sp_rates.log): 9405 rows Concatenated (_sp_rates.log): 16704 rows
Original (_per_species_rates.log): 7300 rows Restored (_per_species

In [82]:
# A_bdmcmc

for i in range(1,3):
    original_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdmcmc/reptilia_pyrate_{i}_A_bdmcmc_corrected_G"
    restored_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdmcmc/A_bdmcmc_restored_logs/reptilia_pyrate_{i}_A_bdmcmc_corrected_restored_G"
    output_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdmcmc/reptilia_pyrate_{i}_A_bdmcmc_corrected_G"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
    print(f"Finished processing reptilia_pyrate_{i}")


 Original (_mcmc.log): 8871 rows, 1544 columns 
 Restored (_mcmc.log): 1499 rows, 1544 columns 
 Concatenated (_mcmc.log): 10370 rows, 1544 columns 

Skipping _ex_rates.log because the file does not exist in the specified directory. Check path.
Skipping _sp_rates.log because the file does not exist in the specified directory. Check path.
Skipping _per_species_rates.log because the file does not exist in the specified directory. Check path.

 Original (_marginal_rates.log): 8871 rows, 899 columns 
 Restored (_marginal_rates.log): 1499 rows, 899 columns 
 Concatenated (_marginal_rates.log): 10370 rows, 899 columns 

Finished processing reptilia_pyrate_1

 Original (_mcmc.log): 8236 rows, 1544 columns 
 Restored (_mcmc.log): 1999 rows, 1544 columns 
 Concatenated (_mcmc.log): 10235 rows, 1544 columns 

Skipping _ex_rates.log because the file does not exist in the specified directory. Check path.
Skipping _sp_rates.log because the file does not exist in the specified directory. Check path

In [83]:
# A_bdmcmc

for i in range(7,11):
    original_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdmcmc/reptilia_pyrate_{i}_A_bdmcmc_corrected_G"
    restored_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdmcmc/A_bdmcmc_restored_logs/reptilia_pyrate_{i}_A_bdmcmc_corrected_restored_G"
    output_log_prefix = f"./reptilia/mcmc_no_predictors/A_bdmcmc/reptilia_pyrate_{i}_A_bdmcmc_corrected_G"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
    print(f"Finished processing reptilia_pyrate_{i}")


 Original (_mcmc.log): 5785 rows, 1544 columns 
 Restored (_mcmc.log): 4499 rows, 1544 columns 
 Concatenated (_mcmc.log): 10284 rows, 1544 columns 

Skipping _ex_rates.log because the file does not exist in the specified directory. Check path.
Skipping _sp_rates.log because the file does not exist in the specified directory. Check path.
Skipping _per_species_rates.log because the file does not exist in the specified directory. Check path.

 Original (_marginal_rates.log): 5785 rows, 899 columns 
 Restored (_marginal_rates.log): 4499 rows, 899 columns 
 Concatenated (_marginal_rates.log): 10284 rows, 899 columns 

Finished processing reptilia_pyrate_7

 Original (_mcmc.log): 5539 rows, 1544 columns 
 Restored (_mcmc.log): 4499 rows, 1544 columns 
 Concatenated (_mcmc.log): 10038 rows, 1544 columns 

Skipping _ex_rates.log because the file does not exist in the specified directory. Check path.
Skipping _sp_rates.log because the file does not exist in the specified directory. Check path

### Synapsida

In [85]:
# A_bdmcmc

for i in range(1,3):
    original_log_prefix = f"./synapsida/mcmc_no_predictors/A_bdmcmc/synapsida_pyrate_{i}_A_bdmcmc_corrected_G"
    restored_log_prefix = f"./synapsida/mcmc_no_predictors/A_bdmcmc/A_bdmcmc_restored_logs/synapsida_pyrate_{i}_A_bdmcmc_corrected_restored_G"
    output_log_prefix = f"./synapsida/mcmc_no_predictors/A_bdmcmc/synapsida_pyrate_{i}_A_bdmcmc_corrected_G"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
    print(f"Finished processing synapsida_pyrate_{i}")


 Original (_mcmc.log): 9023 rows, 1074 columns 
 Restored (_mcmc.log): 999 rows, 1074 columns 
 Concatenated (_mcmc.log): 10022 rows, 1074 columns 

Skipping _ex_rates.log because the file does not exist in the specified directory. Check path.
Skipping _sp_rates.log because the file does not exist in the specified directory. Check path.
Skipping _per_species_rates.log because the file does not exist in the specified directory. Check path.

 Original (_marginal_rates.log): 9023 rows, 932 columns 
 Restored (_marginal_rates.log): 999 rows, 932 columns 
 Concatenated (_marginal_rates.log): 10022 rows, 932 columns 

Finished processing synapsida_pyrate_1

 Original (_mcmc.log): 9865 rows, 1074 columns 
 Restored (_mcmc.log): 199 rows, 1074 columns 
 Concatenated (_mcmc.log): 10064 rows, 1074 columns 

Skipping _ex_rates.log because the file does not exist in the specified directory. Check path.
Skipping _sp_rates.log because the file does not exist in the specified directory. Check path.


In [88]:
# A_bdmcmc

for i in range(7,11):
    original_log_prefix = f"./synapsida/mcmc_no_predictors/A_bdmcmc/synapsida_pyrate_{i}_A_bdmcmc_corrected_G"
    restored_log_prefix = f"./synapsida/mcmc_no_predictors/A_bdmcmc/A_bdmcmc_restored_logs/synapsida_pyrate_{i}_A_bdmcmc_corrected_restored_G"
    output_log_prefix = f"./synapsida/mcmc_no_predictors/A_bdmcmc/synapsida_pyrate_{i}_A_bdmcmc_corrected_G"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
    print(f"Finished processing synapsida_pyrate_{i}")


 Original (_mcmc.log): 6651 rows, 1074 columns 
 Restored (_mcmc.log): 3499 rows, 1074 columns 
 Concatenated (_mcmc.log): 10150 rows, 1074 columns 

Skipping _ex_rates.log because the file does not exist in the specified directory. Check path.
Skipping _sp_rates.log because the file does not exist in the specified directory. Check path.
Skipping _per_species_rates.log because the file does not exist in the specified directory. Check path.

 Original (_marginal_rates.log): 6651 rows, 932 columns 
 Restored (_marginal_rates.log): 3499 rows, 932 columns 
 Concatenated (_marginal_rates.log): 10150 rows, 932 columns 

Finished processing synapsida_pyrate_7

 Original (_mcmc.log): 6469 rows, 1074 columns 
 Restored (_mcmc.log): 3999 rows, 1074 columns 
 Concatenated (_mcmc.log): 10468 rows, 1074 columns 

Skipping _ex_rates.log because the file does not exist in the specified directory. Check path.
Skipping _sp_rates.log because the file does not exist in the specified directory. Check pat

### Temnospondyli

In [87]:
# A_bdmcmc

for i in range(7,11):
    original_log_prefix = f"./temnospondyli/mcmc_no_predictors/A_bdmcmc/temnospondyli_pyrate_{i}_A_bdmcmc_corrected_G"
    restored_log_prefix = f"./temnospondyli/mcmc_no_predictors/A_bdmcmc/A_bdmcmc_restored_logs/temnospondyli_pyrate_{i}_A_bdmcmc_corrected_restored_G"
    output_log_prefix = f"./temnospondyli/mcmc_no_predictors/A_bdmcmc/temnospondyli_pyrate_{i}_A_bdmcmc_corrected_G"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
    print(f"Finished processing temnospondyli_pyrate_{i}")


 Original (_mcmc.log): 8208 rows, 580 columns 
 Restored (_mcmc.log): 1999 rows, 580 columns 
 Concatenated (_mcmc.log): 10207 rows, 580 columns 

Skipping _ex_rates.log because the file does not exist in the specified directory. Check path.
Skipping _sp_rates.log because the file does not exist in the specified directory. Check path.
Skipping _per_species_rates.log because the file does not exist in the specified directory. Check path.

 Original (_marginal_rates.log): 8208 rows, 932 columns 
 Restored (_marginal_rates.log): 1999 rows, 932 columns 
 Concatenated (_marginal_rates.log): 10207 rows, 932 columns 

Finished processing temnospondyli_pyrate_7

 Original (_mcmc.log): 7212 rows, 580 columns 
 Restored (_mcmc.log): 2999 rows, 580 columns 
 Concatenated (_mcmc.log): 10211 rows, 580 columns 

Skipping _ex_rates.log because the file does not exist in the specified directory. Check path.
Skipping _sp_rates.log because the file does not exist in the specified directory. Check path.

## B) mcmc_predictors

### Reptilia

In [73]:
# B_bdnn_stdscaled_only
for i in range(1,2):
    original_log_prefix = f"./reptilia/mcmc_predictors/B_bdnn_stdscaled_only/B_bdnn_stdscaled_only_source_logs_for_concatenation/reptilia_pyrate_{i}_B_stdscaled_only_G_BD1-1_BDNN_16_8TVc"
    restored_log_prefix = f"./reptilia/mcmc_predictors/B_bdnn_stdscaled_only/B_bdnn_stdscaled_only_source_logs_for_concatenation/reptilia_pyrate_{i}_B_stdscaled_only_RESTORED_G_BD1-1_BDNN_16_8TVc"
    output_log_prefix = f"./reptilia/mcmc_predictors/B_bdnn_stdscaled_only/reptilia_pyrate_{i}_B_stdscaled_only_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
    print(f"Finished processing reptilia_pyrate_{i}")

Original (_mcmc.log): 7744 rows 
 Restored (_mcmc.log): 2999 rows 
 Concatenated (_mcmc.log): 10743 rows
Original (_ex_rates.log): 7743 rows 
 Restored (_ex_rates.log): 2998 rows 
 Concatenated (_ex_rates.log): 10741 rows
Original (_sp_rates.log): 7743 rows 
 Restored (_sp_rates.log): 2998 rows 
 Concatenated (_sp_rates.log): 10741 rows
Original (_per_species_rates.log): 7744 rows 
 Restored (_per_species_rates.log): 2999 rows 
 Concatenated (_per_species_rates.log): 10743 rows
Skipping _marginal_rates.log because the file does not exist in the specified directory. Check path.
Finished processing reptilia_pyrate_1


### Synapsida

In [38]:
# B_bdnn_stdscaled_boxcox

for i in range(7,8):
    original_boxcox_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_boxcox/synapsida_pyrate_{i}_B_stdscaled_boxcox_G_BD1-1_BDNN_16_8TVc"
    restored_boxcox_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_boxcox/B_bdnn_stdscaled_boxcox_restored_logs/synapsida_pyrate_{i}_B_stdscaled_boxcox_restored_G_BD1-1_BDNN_16_8TVc"
    output_boxcox_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_boxcox/B_bdnn_stdscaled_boxcox_concatenated_logs/synapsida_pyrate_{i}_B_stdscaled_boxcox_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_boxcox_prefix, restored_boxcox_prefix, output_boxcox_prefix, 19900)
    print(f"Finished processing synapsida_pyrate_{i}")

C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 6656 rows Restored (_mcmc.log): 13302 rows Concatenated (_mcmc.log): 19958 rows Concatenated_final (_mcmc.log): 19900 rows
Original (_ex_rates.log): 6655 rows Restored (_ex_rates.log): 13301 rows Concatenated (_ex_rates.log): 19956 rows Concatenated_final (_ex_rates.log): 19900 rows
Original (_sp_rates.log): 6655 rows Restored (_sp_rates.log): 13301 rows Concatenated (_sp_rates.log): 19956 rows Concatenated_final (_sp_rates.log): 19900 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 6656 rows Restored (_per_species_rates.log): 13302 rows Concatenated (_per_species_rates.log): 19958 rows Concatenated_final (_per_species_rates.log): 19900 rows
Finished processing synapsida_pyrate_7


In [42]:
# B_bdnn_stdscaled_boxcox

for i in range(7,8):
    original_boxcox_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_boxcox/B_bdnn_stdscaled_boxcox_concatenated_logs/synapsida_pyrate_{i}_B_stdscaled_boxcox_G_BDS_BDNN_16_8TVc_CONCAT"
    restored_boxcox_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_boxcox/B_bdnn_stdscaled_boxcox_concatenated_logs/pyrate_mcmc_logs/synapsida_pyrate_{i}_B_stdscaled_boxcox_rerestoration_G_BD1-1_BDNN_16_8TVc"
    output_boxcox_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_boxcox/B_bdnn_stdscaled_boxcox_concatenated_logs/synapsida_pyrate_{i}_B_stdscaled_boxcox_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_boxcox_prefix, restored_boxcox_prefix, output_boxcox_prefix, 19900)
    print(f"Finished processing synapsida_pyrate_{i}")

C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 19900 rows Restored (_mcmc.log): 99 rows Concatenated (_mcmc.log): 19999 rows Concatenated_final (_mcmc.log): 19900 rows
Original (_ex_rates.log): 19900 rows Restored (_ex_rates.log): 98 rows Concatenated (_ex_rates.log): 19998 rows Concatenated_final (_ex_rates.log): 19900 rows
Original (_sp_rates.log): 19900 rows Restored (_sp_rates.log): 98 rows Concatenated (_sp_rates.log): 19998 rows Concatenated_final (_sp_rates.log): 19900 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 19900 rows Restored (_per_species_rates.log): 99 rows Concatenated (_per_species_rates.log): 19999 rows Concatenated_final (_per_species_rates.log): 19900 rows
Finished processing synapsida_pyrate_7


In [58]:
# B_bdnn_stdscaled_only

for i in range(1,11):
    original_only_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_only/synapsida_pyrate_{i}_B_stdscaled_only_G_BD1-1_BDNN_16_8TVc"
    restored_only_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_only/B_bdnn_stdscaled_only_restored_logs/synapsida_pyrate_{i}_B_stdscaled_only_restored_G_BD1-1_BDNN_16_8TVc"
    output_only_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_only/synapsida_pyrate_{i}_B_stdscaled_only_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_only_prefix, restored_only_prefix, output_only_prefix)
    print(f"Finished processing synapsida_pyrate_{i}")

Original (_mcmc.log): 6552 rows Restored (_mcmc.log): 13208 rows Concatenated (_mcmc.log): 19760 rows
Original (_ex_rates.log): 6551 rows Restored (_ex_rates.log): 13207 rows Concatenated (_ex_rates.log): 19758 rows
Original (_sp_rates.log): 6551 rows Restored (_sp_rates.log): 13207 rows Concatenated (_sp_rates.log): 19758 rows
Original (_per_species_rates.log): 6552 rows Restored (_per_species_rates.log): 13208 rows Concatenated (_per_species_rates.log): 19760 rows
Skipping _marginal_rates.log because the file does not exist in the specified directory. Check path.
Finished processing synapsida_pyrate_1
Original (_mcmc.log): 6959 rows Restored (_mcmc.log): 12057 rows Concatenated (_mcmc.log): 19016 rows
Original (_ex_rates.log): 6958 rows Restored (_ex_rates.log): 12056 rows Concatenated (_ex_rates.log): 19014 rows
Original (_sp_rates.log): 6958 rows Restored (_sp_rates.log): 12056 rows Concatenated (_sp_rates.log): 19014 rows
Original (_per_species_rates.log): 6959 rows Restored (_per

In [61]:
# B_bdnn_stdscaled_log

for i in range(1,11):
    original_log_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_log/synapsida_pyrate_{i}_B_stdscaled_log_G_BD1-1_BDNN_16_8TVc"
    restored_log_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_log/B_bdnn_stdscaled_log_restored_logs/synapsida_pyrate_{i}_B_stdscaled_log_restored_G_BD1-1_BDNN_16_8TVc"
    output_log_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_log/synapsida_pyrate_{i}_B_stdscaled_log_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
    print(f"Finished processing synapsida_pyrate_{i}")

Original (_mcmc.log): 6559 rows Restored (_mcmc.log): 13738 rows Concatenated (_mcmc.log): 20297 rows
Original (_ex_rates.log): 6558 rows Restored (_ex_rates.log): 13737 rows Concatenated (_ex_rates.log): 20295 rows
Original (_sp_rates.log): 6558 rows Restored (_sp_rates.log): 13737 rows Concatenated (_sp_rates.log): 20295 rows
Original (_per_species_rates.log): 6559 rows Restored (_per_species_rates.log): 13738 rows Concatenated (_per_species_rates.log): 20297 rows
Skipping _marginal_rates.log because the file does not exist in the specified directory. Check path.
Finished processing synapsida_pyrate_1
Original (_mcmc.log): 6941 rows Restored (_mcmc.log): 13999 rows Concatenated (_mcmc.log): 20940 rows
Original (_ex_rates.log): 6940 rows Restored (_ex_rates.log): 13998 rows Concatenated (_ex_rates.log): 20938 rows
Original (_sp_rates.log): 6940 rows Restored (_sp_rates.log): 13998 rows Concatenated (_sp_rates.log): 20938 rows
Original (_per_species_rates.log): 6941 rows Restored (_per

In [62]:
# B_bdnn_stdscaled_cbrt

for i in range(1,11):
    original_cbrt_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_cbrt/synapsida_pyrate_{i}_B_stdscaled_cbrt_G_BD1-1_BDNN_16_8TVc"
    restored_cbrt_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_cbrt/B_bdnn_stdscaled_cbrt_restored_logs/synapsida_pyrate_{i}_B_stdscaled_cbrt_restored_G_BD1-1_BDNN_16_8TVc"
    output_cbrt_prefix = f"./synapsida/mcmc_predictors/B_bdnn_stdscaled_cbrt/synapsida_pyrate_{i}_B_stdscaled_cbrt_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_cbrt_prefix, restored_cbrt_prefix, output_cbrt_prefix)
    print(f"Finished processing synapsida_pyrate_{i}")

Original (_mcmc.log): 6675 rows Restored (_mcmc.log): 11630 rows Concatenated (_mcmc.log): 18305 rows
Original (_ex_rates.log): 6674 rows Restored (_ex_rates.log): 11629 rows Concatenated (_ex_rates.log): 18303 rows
Original (_sp_rates.log): 6674 rows Restored (_sp_rates.log): 11629 rows Concatenated (_sp_rates.log): 18303 rows
Original (_per_species_rates.log): 6675 rows Restored (_per_species_rates.log): 11630 rows Concatenated (_per_species_rates.log): 18305 rows
Skipping _marginal_rates.log because the file does not exist in the specified directory. Check path.
Finished processing synapsida_pyrate_1
Original (_mcmc.log): 6695 rows Restored (_mcmc.log): 13999 rows Concatenated (_mcmc.log): 20694 rows
Original (_ex_rates.log): 6694 rows Restored (_ex_rates.log): 13998 rows Concatenated (_ex_rates.log): 20692 rows
Original (_sp_rates.log): 6694 rows Restored (_sp_rates.log): 13998 rows Concatenated (_sp_rates.log): 20692 rows
Original (_per_species_rates.log): 6695 rows Restored (_per

### Temnospondyli

In [23]:
# B_bdnn_stdscaled_only
for i in range(1,11):
    original_log_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_only/temnospondyli_pyrate_{i}_B_stdscaled_only_G_BDS_BDNN_16_8TVc"
    restored_log_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_only/B_bdnn_stdscaled_only_restored_logs/temnospondyli_pyrate_{i}_B_stdscaled_only_restored_G_BD1-1_BDNN_16_8TVc"
    output_log_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_only/B_bdnn_stdscaled_only_concatenated_logs/temnospondyli_pyrate_{i}_B_stdscaled_only_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
    print(f"Finished processing temnospondyli_pyrate_{i}")

C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 1425 rows Restored (_mcmc.log): 9999 rows Concatenated (_mcmc.log): 11424 rows Concatenated_10k (_mcmc.log): 10000 rows
Original (_ex_rates.log): 1424 rows Restored (_ex_rates.log): 9998 rows Concatenated (_ex_rates.log): 11422 rows Concatenated_10k (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 1424 rows Restored (_sp_rates.log): 9998 rows Concatenated (_sp_rates.log): 11422 rows Concatenated_10k (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 1425 rows Restored (_per_species_rates.log): 9999 rows Concatenated (_per_species_rates.log): 11424 rows Concatenated_10k (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_1


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 1399 rows Restored (_mcmc.log): 9999 rows Concatenated (_mcmc.log): 11398 rows Concatenated_10k (_mcmc.log): 10000 rows
Original (_ex_rates.log): 1398 rows Restored (_ex_rates.log): 9998 rows Concatenated (_ex_rates.log): 11396 rows Concatenated_10k (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 1398 rows Restored (_sp_rates.log): 9998 rows Concatenated (_sp_rates.log): 11396 rows Concatenated_10k (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 1399 rows Restored (_per_species_rates.log): 9999 rows Concatenated (_per_species_rates.log): 11398 rows Concatenated_10k (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_2


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 2798 rows Restored (_mcmc.log): 9999 rows Concatenated (_mcmc.log): 12797 rows Concatenated_10k (_mcmc.log): 10000 rows
Original (_ex_rates.log): 2797 rows Restored (_ex_rates.log): 9998 rows Concatenated (_ex_rates.log): 12795 rows Concatenated_10k (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 2797 rows Restored (_sp_rates.log): 9998 rows Concatenated (_sp_rates.log): 12795 rows Concatenated_10k (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 2798 rows Restored (_per_species_rates.log): 9999 rows Concatenated (_per_species_rates.log): 12797 rows Concatenated_10k (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_3


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 5842 rows Restored (_mcmc.log): 9999 rows Concatenated (_mcmc.log): 15841 rows Concatenated_10k (_mcmc.log): 10000 rows
Original (_ex_rates.log): 5841 rows Restored (_ex_rates.log): 9998 rows Concatenated (_ex_rates.log): 15839 rows Concatenated_10k (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 5841 rows Restored (_sp_rates.log): 9998 rows Concatenated (_sp_rates.log): 15839 rows Concatenated_10k (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 5842 rows Restored (_per_species_rates.log): 9999 rows Concatenated (_per_species_rates.log): 15841 rows Concatenated_10k (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_4


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 5891 rows Restored (_mcmc.log): 9999 rows Concatenated (_mcmc.log): 15890 rows Concatenated_10k (_mcmc.log): 10000 rows
Original (_ex_rates.log): 5890 rows Restored (_ex_rates.log): 9998 rows Concatenated (_ex_rates.log): 15888 rows Concatenated_10k (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 5890 rows Restored (_sp_rates.log): 9998 rows Concatenated (_sp_rates.log): 15888 rows Concatenated_10k (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 5891 rows Restored (_per_species_rates.log): 9999 rows Concatenated (_per_species_rates.log): 15890 rows Concatenated_10k (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_5


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 6035 rows Restored (_mcmc.log): 9999 rows Concatenated (_mcmc.log): 16034 rows Concatenated_10k (_mcmc.log): 10000 rows
Original (_ex_rates.log): 6034 rows Restored (_ex_rates.log): 9998 rows Concatenated (_ex_rates.log): 16032 rows Concatenated_10k (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 6034 rows Restored (_sp_rates.log): 9998 rows Concatenated (_sp_rates.log): 16032 rows Concatenated_10k (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 6035 rows Restored (_per_species_rates.log): 9999 rows Concatenated (_per_species_rates.log): 16034 rows Concatenated_10k (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_6


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 5951 rows Restored (_mcmc.log): 9999 rows Concatenated (_mcmc.log): 15950 rows Concatenated_10k (_mcmc.log): 10000 rows
Original (_ex_rates.log): 5950 rows Restored (_ex_rates.log): 9998 rows Concatenated (_ex_rates.log): 15948 rows Concatenated_10k (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 5950 rows Restored (_sp_rates.log): 9998 rows Concatenated (_sp_rates.log): 15948 rows Concatenated_10k (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 5951 rows Restored (_per_species_rates.log): 9999 rows Concatenated (_per_species_rates.log): 15950 rows Concatenated_10k (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_7


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 5991 rows Restored (_mcmc.log): 9999 rows Concatenated (_mcmc.log): 15990 rows Concatenated_10k (_mcmc.log): 10000 rows
Original (_ex_rates.log): 5990 rows Restored (_ex_rates.log): 9998 rows Concatenated (_ex_rates.log): 15988 rows Concatenated_10k (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 5990 rows Restored (_sp_rates.log): 9998 rows Concatenated (_sp_rates.log): 15988 rows Concatenated_10k (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 5991 rows Restored (_per_species_rates.log): 9999 rows Concatenated (_per_species_rates.log): 15990 rows Concatenated_10k (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_8


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 4408 rows Restored (_mcmc.log): 9999 rows Concatenated (_mcmc.log): 14407 rows Concatenated_10k (_mcmc.log): 10000 rows
Original (_ex_rates.log): 4407 rows Restored (_ex_rates.log): 9998 rows Concatenated (_ex_rates.log): 14405 rows Concatenated_10k (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 4407 rows Restored (_sp_rates.log): 9998 rows Concatenated (_sp_rates.log): 14405 rows Concatenated_10k (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 4408 rows Restored (_per_species_rates.log): 9999 rows Concatenated (_per_species_rates.log): 14407 rows Concatenated_10k (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_9


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 5631 rows Restored (_mcmc.log): 9999 rows Concatenated (_mcmc.log): 15630 rows Concatenated_10k (_mcmc.log): 10000 rows
Original (_ex_rates.log): 5630 rows Restored (_ex_rates.log): 9998 rows Concatenated (_ex_rates.log): 15628 rows Concatenated_10k (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 5630 rows Restored (_sp_rates.log): 9998 rows Concatenated (_sp_rates.log): 15628 rows Concatenated_10k (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['iterations'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 5631 rows Restored (_per_species_rates.log): 9999 rows Concatenated (_per_species_rates.log): 15630 rows Concatenated_10k (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_10


In [45]:
# B_bdnn_stdscaled_log
for i in range(8, 9):
    original_log_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_log/B_bdnn_stdscaled_log_concatenated_logs/temnospondyli_pyrate_{i}_B_stdscaled_log_G_BDS_BDNN_16_8TVc_CONCAT"
    restored_log_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_log/B_bdnn_stdscaled_log_concatenated_logs/pyrate_mcmc_logs/temnospondyli_pyrate_{i}_B_stdscaled_log_rerestorations_again_G_BD1-1_BDNN_16_8TVc"
    output_log_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_log/B_bdnn_stdscaled_log_concatenated_logs/temnospondyli_pyrate_{i}_B_stdscaled_log_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix, 10000)
    print(f"Finished processing temnospondyli_pyrate_{i}")

    # Replicates 4 and 8 did not have enough combined iterations in the original and restored logs to reach 100 mill, so I did a 
    # "rerestoration" of them, and concatenated those rerestored logs with the original logs to get to 100 mill iterations

C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 9700 rows Restored (_mcmc.log): 599 rows Concatenated (_mcmc.log): 10299 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 9700 rows Restored (_ex_rates.log): 598 rows Concatenated (_ex_rates.log): 10298 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 9700 rows Restored (_sp_rates.log): 598 rows Concatenated (_sp_rates.log): 10298 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 9700 rows Restored (_per_species_rates.log): 599 rows Concatenated (_per_species_rates.log): 10299 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_8


In [13]:
# B_bdnn_stdscaled_boxcox

for i in range(1,11):
    original_boxcox_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_boxcox/temnospondyli_pyrate_{i}_B_stdscaled_boxcox_G_BDS_BDNN_16_8TVc"
    restored_boxcox_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_boxcox/B_bdnn_stdscaled_boxcox_restored_logs/temnospondyli_pyrate_{i}_B_stdscaled_boxcox_restored_G_BD1-1_BDNN_16_8TVc"
    output_boxcox_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_boxcox/B_bdnn_stdscaled_boxcox_concatenated_logs/temnospondyli_pyrate_{i}_B_stdscaled_boxcox_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_boxcox_prefix, restored_boxcox_prefix, output_boxcox_prefix, 10000)
    print(f"Finished processing temnospondyli_pyrate_{i}")

C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 5608 rows Restored (_mcmc.log): 8810 rows Concatenated (_mcmc.log): 14418 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 5607 rows Restored (_ex_rates.log): 8809 rows Concatenated (_ex_rates.log): 14416 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 5607 rows Restored (_sp_rates.log): 8809 rows Concatenated (_sp_rates.log): 14416 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 5608 rows Restored (_per_species_rates.log): 8810 rows Concatenated (_per_species_rates.log): 14418 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_1


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 6037 rows Restored (_mcmc.log): 8574 rows Concatenated (_mcmc.log): 14611 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 6036 rows Restored (_ex_rates.log): 8573 rows Concatenated (_ex_rates.log): 14609 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 6036 rows Restored (_sp_rates.log): 8573 rows Concatenated (_sp_rates.log): 14609 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 6037 rows Restored (_per_species_rates.log): 8574 rows Concatenated (_per_species_rates.log): 14611 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_2


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 2293 rows Restored (_mcmc.log): 8764 rows Concatenated (_mcmc.log): 11057 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 2292 rows Restored (_ex_rates.log): 8763 rows Concatenated (_ex_rates.log): 11055 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 2292 rows Restored (_sp_rates.log): 8763 rows Concatenated (_sp_rates.log): 11055 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 2293 rows Restored (_per_species_rates.log): 8764 rows Concatenated (_per_species_rates.log): 11057 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_3


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 1971 rows Restored (_mcmc.log): 9295 rows Concatenated (_mcmc.log): 11266 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 1970 rows Restored (_ex_rates.log): 9294 rows Concatenated (_ex_rates.log): 11264 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 1970 rows Restored (_sp_rates.log): 9294 rows Concatenated (_sp_rates.log): 11264 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 1971 rows Restored (_per_species_rates.log): 9295 rows Concatenated (_per_species_rates.log): 11266 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_4


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 7349 rows Restored (_mcmc.log): 9460 rows Concatenated (_mcmc.log): 16809 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 7348 rows Restored (_ex_rates.log): 9459 rows Concatenated (_ex_rates.log): 16807 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 7348 rows Restored (_sp_rates.log): 9459 rows Concatenated (_sp_rates.log): 16807 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 7349 rows Restored (_per_species_rates.log): 9460 rows Concatenated (_per_species_rates.log): 16809 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_5


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 6037 rows Restored (_mcmc.log): 8964 rows Concatenated (_mcmc.log): 15001 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 6036 rows Restored (_ex_rates.log): 8963 rows Concatenated (_ex_rates.log): 14999 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 6036 rows Restored (_sp_rates.log): 8963 rows Concatenated (_sp_rates.log): 14999 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 6037 rows Restored (_per_species_rates.log): 8964 rows Concatenated (_per_species_rates.log): 15001 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_6


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 6060 rows Restored (_mcmc.log): 9026 rows Concatenated (_mcmc.log): 15086 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 6059 rows Restored (_ex_rates.log): 9025 rows Concatenated (_ex_rates.log): 15084 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 6059 rows Restored (_sp_rates.log): 9025 rows Concatenated (_sp_rates.log): 15084 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 6060 rows Restored (_per_species_rates.log): 9026 rows Concatenated (_per_species_rates.log): 15086 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_7


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 7039 rows Restored (_mcmc.log): 8872 rows Concatenated (_mcmc.log): 15911 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 7038 rows Restored (_ex_rates.log): 8871 rows Concatenated (_ex_rates.log): 15909 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 7038 rows Restored (_sp_rates.log): 8871 rows Concatenated (_sp_rates.log): 15909 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 7039 rows Restored (_per_species_rates.log): 8872 rows Concatenated (_per_species_rates.log): 15911 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_8


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 5715 rows Restored (_mcmc.log): 9401 rows Concatenated (_mcmc.log): 15116 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 5714 rows Restored (_ex_rates.log): 9400 rows Concatenated (_ex_rates.log): 15114 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 5714 rows Restored (_sp_rates.log): 9400 rows Concatenated (_sp_rates.log): 15114 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 5715 rows Restored (_per_species_rates.log): 9401 rows Concatenated (_per_species_rates.log): 15116 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_9


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 6252 rows Restored (_mcmc.log): 9431 rows Concatenated (_mcmc.log): 15683 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 6251 rows Restored (_ex_rates.log): 9430 rows Concatenated (_ex_rates.log): 15681 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 6251 rows Restored (_sp_rates.log): 9430 rows Concatenated (_sp_rates.log): 15681 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 6252 rows Restored (_per_species_rates.log): 9431 rows Concatenated (_per_species_rates.log): 15683 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_10


In [20]:
# B_bdnn_stdscaled_cbrt
for i in range(4,9):
    original_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_G_BDS_BDNN_16_8TVc"
    restored_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/B_bdnn_stdscaled_cbrt_restored_logs/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_restored_G_BD1-1_BDNN_16_8TVc"
    output_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/B_bdnn_stdscaled_cbrt_concatenated_logs/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_cbrt_prefix, restored_cbrt_prefix, output_cbrt_prefix, 10000)
    print(f"Finished processing temnospondyli_pyrate_{i}")

C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 5606 rows Restored (_mcmc.log): 8602 rows Concatenated (_mcmc.log): 14208 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 5605 rows Restored (_ex_rates.log): 8601 rows Concatenated (_ex_rates.log): 14206 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 5605 rows Restored (_sp_rates.log): 8601 rows Concatenated (_sp_rates.log): 14206 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 5606 rows Restored (_per_species_rates.log): 8602 rows Concatenated (_per_species_rates.log): 14208 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_4


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 700 rows Restored (_mcmc.log): 9325 rows Concatenated (_mcmc.log): 10025 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 699 rows Restored (_ex_rates.log): 9324 rows Concatenated (_ex_rates.log): 10023 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 699 rows Restored (_sp_rates.log): 9324 rows Concatenated (_sp_rates.log): 10023 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 700 rows Restored (_per_species_rates.log): 9325 rows Concatenated (_per_species_rates.log): 10025 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_5


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 700 rows Restored (_mcmc.log): 9494 rows Concatenated (_mcmc.log): 10194 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 699 rows Restored (_ex_rates.log): 9493 rows Concatenated (_ex_rates.log): 10192 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 699 rows Restored (_sp_rates.log): 9493 rows Concatenated (_sp_rates.log): 10192 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 700 rows Restored (_per_species_rates.log): 9494 rows Concatenated (_per_species_rates.log): 10194 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_6


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 701 rows Restored (_mcmc.log): 9570 rows Concatenated (_mcmc.log): 10271 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 700 rows Restored (_ex_rates.log): 9569 rows Concatenated (_ex_rates.log): 10269 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 700 rows Restored (_sp_rates.log): 9569 rows Concatenated (_sp_rates.log): 10269 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 701 rows Restored (_per_species_rates.log): 9570 rows Concatenated (_per_species_rates.log): 10271 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_7


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 3226 rows Restored (_mcmc.log): 9824 rows Concatenated (_mcmc.log): 13050 rows Concatenated_final (_mcmc.log): 10000 rows
Original (_ex_rates.log): 3225 rows Restored (_ex_rates.log): 9823 rows Concatenated (_ex_rates.log): 13048 rows Concatenated_final (_ex_rates.log): 10000 rows
Original (_sp_rates.log): 3225 rows Restored (_sp_rates.log): 9823 rows Concatenated (_sp_rates.log): 13048 rows Concatenated_final (_sp_rates.log): 10000 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 3226 rows Restored (_per_species_rates.log): 9824 rows Concatenated (_per_species_rates.log): 13050 rows Concatenated_final (_per_species_rates.log): 10000 rows
Finished processing temnospondyli_pyrate_8


In [22]:
# B_bdnn_stdscaled_cbrt
for i in range(2, 4):
    original_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_G_BDS_BDNN_16_8TVc"
    restored_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/B_bdnn_stdscaled_cbrt_restored_logs/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_restored_G_BD1-1_BDNN_16_8TVc"
    output_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/B_bdnn_stdscaled_cbrt_concatenated_logs/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_cbrt_prefix, restored_cbrt_prefix, output_cbrt_prefix, 9300)
    print(f"Finished processing temnospondyli_pyrate_{i}")

C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 700 rows Restored (_mcmc.log): 8726 rows Concatenated (_mcmc.log): 9426 rows Concatenated_final (_mcmc.log): 9300 rows
Original (_ex_rates.log): 699 rows Restored (_ex_rates.log): 8725 rows Concatenated (_ex_rates.log): 9424 rows Concatenated_final (_ex_rates.log): 9300 rows
Original (_sp_rates.log): 699 rows Restored (_sp_rates.log): 8725 rows Concatenated (_sp_rates.log): 9424 rows Concatenated_final (_sp_rates.log): 9300 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 700 rows Restored (_per_species_rates.log): 8726 rows Concatenated (_per_species_rates.log): 9426 rows Concatenated_final (_per_species_rates.log): 9300 rows
Finished processing temnospondyli_pyrate_2


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 700 rows Restored (_mcmc.log): 8623 rows Concatenated (_mcmc.log): 9323 rows Concatenated_final (_mcmc.log): 9300 rows
Original (_ex_rates.log): 699 rows Restored (_ex_rates.log): 8622 rows Concatenated (_ex_rates.log): 9321 rows Concatenated_final (_ex_rates.log): 9300 rows
Original (_sp_rates.log): 699 rows Restored (_sp_rates.log): 8622 rows Concatenated (_sp_rates.log): 9321 rows Concatenated_final (_sp_rates.log): 9300 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 700 rows Restored (_per_species_rates.log): 8623 rows Concatenated (_per_species_rates.log): 9323 rows Concatenated_final (_per_species_rates.log): 9300 rows
Finished processing temnospondyli_pyrate_3


In [28]:
# B_bdnn_stdscaled_cbrt
for i in range(9, 10):
    original_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/B_bdnn_stdscaled_cbrt_concatenated_logs/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_G_BDS_BDNN_16_8TVc_CONCAT"
    restored_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/B_bdnn_stdscaled_cbrt_concatenated_logs/pyrate_mcmc_logs/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_restored_again_G_BD1-1_BDNN_16_8TVc"
    output_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/B_bdnn_stdscaled_cbrt_concatenated_logs/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_cbrt_prefix, restored_cbrt_prefix, output_cbrt_prefix, 10600)
    print(f"Finished processing temnospondyli_pyrate_{i}")

C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['it'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_mcmc.log): 9900 rows Restored (_mcmc.log): 799 rows Concatenated (_mcmc.log): 10699 rows Concatenated_final (_mcmc.log): 10600 rows
Original (_ex_rates.log): 9900 rows Restored (_ex_rates.log): 798 rows Concatenated (_ex_rates.log): 10698 rows Concatenated_final (_ex_rates.log): 10600 rows
Original (_sp_rates.log): 9900 rows Restored (_sp_rates.log): 798 rows Concatenated (_sp_rates.log): 10698 rows Concatenated_final (_sp_rates.log): 10600 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 9900 rows Restored (_per_species_rates.log): 799 rows Concatenated (_per_species_rates.log): 10699 rows Concatenated_final (_per_species_rates.log): 10600 rows
Finished processing temnospondyli_pyrate_9


In [40]:
# B_bdnn_stdscaled_cbrt
for i in range(10, 11):
    original_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_G_BDS_BDNN_16_8TVc"
    restored_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/B_bdnn_stdscaled_cbrt_restored_logs/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_restored_G_BD1-1_BDNN_16_8TVc"
    output_cbrt_prefix = f"./temnospondyli/mcmc_predictors/B_bdnn_stdscaled_cbrt/B_bdnn_stdscaled_cbrt_concatenated_logs/temnospondyli_pyrate_{i}_B_stdscaled_cbrt_G_BDS_BDNN_16_8TVc"
    results = concatenate_logs(original_cbrt_prefix, restored_cbrt_prefix, output_cbrt_prefix, 11398)
    print(f"Finished processing temnospondyli_pyrate_{i}")

Original (_mcmc.log): 1399 rows Restored (_mcmc.log): 9999 rows Concatenated (_mcmc.log): 11398 rows Concatenated_final (_mcmc.log): 11398 rows
Original (_ex_rates.log): 1398 rows Restored (_ex_rates.log): 9998 rows Concatenated (_ex_rates.log): 11396 rows Concatenated_final (_ex_rates.log): 11396 rows
Original (_sp_rates.log): 1398 rows Restored (_sp_rates.log): 9998 rows Concatenated (_sp_rates.log): 11396 rows Concatenated_final (_sp_rates.log): 11396 rows


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_18120\2699335858.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_final['iterations'] = np.arange(0, concatenated_final.shape[0] * 10000, 10000)


Original (_per_species_rates.log): 1399 rows Restored (_per_species_rates.log): 9999 rows Concatenated (_per_species_rates.log): 11398 rows Concatenated_final (_per_species_rates.log): 11398 rows
Finished processing temnospondyli_pyrate_10


In [ ]:
# B_covar_rjmcmc_notranslate
# Also run for replicate 1
# ONly mcmc
for i in range(6,11):
    original_log_prefix = f"./temnospondyli/mcmc_predictors/B_covar_rjmcmc_notranslate/temnospondyli_pyrate_{i}_G_COVhprj"
    restored_log_prefix = f"./temnospondyli/mcmc_predictors/B_covar_rjmcmc_notranslate/B_covar_rjmcmc_notranslate_restored_logs/temnospondyli_pyrate_{i}_B_notranslate_restored_G_COVhprj"
    output_log_prefix = f"./temnospondyli/mcmc_predictors/B_covar_rjmcmc_notranslate/B_covar_rjmcmc_notranslate_concatenated_logs/temnospondyli_pyrate_{i}_B_notranslate_restored_G_COVhprj"
    results = concatenate_logs(original_log_prefix, restored_log_prefix, output_log_prefix)
    print(f"Finished processing temnospondyli_pyrate_{i}")

C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 5398 rows Restored (_mcmc.log): 4999 rows Concatenated (_mcmc.log): 10397 rows Concatenated_10k (_mcmc.log): 10000 rows
Skipping _ex_rates.log because of a parsing error in the original log file: Error tokenizing data. C error: Expected 5 fields in line 3, saw 11

Skipping _sp_rates.log because of a parsing error in the original log file: Error tokenizing data. C error: Expected 11 fields in line 9, saw 15

Skipping _per_species_rates.log because the file does not exist.
Finished processing temnospondyli_pyrate_6


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 6557 rows Restored (_mcmc.log): 3999 rows Concatenated (_mcmc.log): 10556 rows Concatenated_10k (_mcmc.log): 10000 rows
Skipping _ex_rates.log because of a parsing error in the original log file: Error tokenizing data. C error: Expected 7 fields in line 7, saw 9

Skipping _sp_rates.log because of a parsing error in the original log file: Error tokenizing data. C error: Expected 9 fields in line 3, saw 11

Skipping _per_species_rates.log because the file does not exist.
Finished processing temnospondyli_pyrate_7


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 5853 rows Restored (_mcmc.log): 4999 rows Concatenated (_mcmc.log): 10852 rows Concatenated_10k (_mcmc.log): 10000 rows
Skipping _ex_rates.log because of a parsing error in the original log file: Error tokenizing data. C error: Expected 9 fields in line 8, saw 11

Skipping _sp_rates.log because of a parsing error in the original log file: Error tokenizing data. C error: Expected 13 fields in line 8, saw 15

Skipping _per_species_rates.log because the file does not exist.
Finished processing temnospondyli_pyrate_8


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 5888 rows Restored (_mcmc.log): 4999 rows Concatenated (_mcmc.log): 10887 rows Concatenated_10k (_mcmc.log): 10000 rows
Skipping _ex_rates.log because of a parsing error in the original log file: Error tokenizing data. C error: Expected 5 fields in line 3, saw 11

Skipping _sp_rates.log because of a parsing error in the original log file: Error tokenizing data. C error: Expected 11 fields in line 3, saw 13

Skipping _per_species_rates.log because the file does not exist.
Finished processing temnospondyli_pyrate_9


C:\Users\SimoesLabAdmin\AppData\Local\Temp\ipykernel_26764\272809452.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  concatenated_10k['it'] = np.arange(0, concatenated_10k.shape[0] * 10000, 10000)


Original (_mcmc.log): 6299 rows Restored (_mcmc.log): 3999 rows Concatenated (_mcmc.log): 10298 rows Concatenated_10k (_mcmc.log): 10000 rows
Skipping _ex_rates.log because of a parsing error in the original log file: Error tokenizing data. C error: Expected 7 fields in line 4, saw 9

Skipping _sp_rates.log because of a parsing error in the original log file: Error tokenizing data. C error: Expected 13 fields in line 22, saw 15

Skipping _per_species_rates.log because the file does not exist.
Finished processing temnospondyli_pyrate_10


### PROBLEM: Covar RJMCMC NO TRANSLATE

In [ ]:
#** PROBLEM: THE B_covar_rjmcmc_notranslate sp and ex rates logs have a different number of columns in each row (b/c of the RJMCMC)
# The function as it is now will just skip over those logs, but I want to be able to include them in the concatenation

# As of now, this isn't an issue because I have B_covar_rjmcmc runs that ARE complete
# B_covar_rjmcmc runs are the exact same as the B_covar_rjmcmc_notranslate, they just use -translate -175 (which is probably why they finished completely as opposed
# to B_covar_rjmcmc_notranslate))

# I just moved the notranslate runs into "old_B_logs" directory. 
# Also reptilia doesn't even have B_covar_rjmcmc_notranslate runs, so it's not worth concatenating its files for just syn and tem anyway

B_covar_rjmcmc_notranslate_tem_1 = pd.read_csv("./temnospondyli/mcmc_predictors/B_covar_rjmcmc_notranslate/temnospondyli_pyrate_1_G_COVhprj_ex_rates.log", sep="\t", header=0)
B_covar_rjmcmc_notranslate_tem_1.head()

# Synapsida C_Covar Issue
Synapsida C_covar has an issue where marginal_rates for rep 5 has 403 cols, and all the other reps' marginal_rates have 406. Encountered this issue when trying to combine log files with -combLogRJ

-combLog also doesn't work

Showing that this is true + figuring out which cols are not shared + showing that this is not true for reptilia or temnospondyli

In [ ]:
syn_1_marginal_rates = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_1_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
syn_2_marginal_rates = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_2_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
syn_3_marginal_rates = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_3_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
syn_4_marginal_rates = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_4_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
syn_5_marginal_rates = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_5_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
syn_6_marginal_rates = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_6_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
syn_7_marginal_rates = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_7_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
syn_8_marginal_rates = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_8_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
syn_9_marginal_rates = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_9_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
syn_10_marginal_rates = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_10_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)

# Seeing the rows and columns of every marginal_rates log
syn_1_marginal_rates.shape, syn_2_marginal_rates.shape, syn_3_marginal_rates.shape, syn_4_marginal_rates.shape, syn_5_marginal_rates.shape, syn_6_marginal_rates.shape, syn_7_marginal_rates.shape, syn_8_marginal_rates.shape, syn_9_marginal_rates.shape, syn_10_marginal_rates.shape

((10000, 407),
 (10000, 407),
 (10000, 407),
 (10000, 407),
 (10000, 404),
 (10000, 407),
 (10000, 407),
 (10000, 407),
 (10000, 407),
 (10000, 407))

In [82]:
syn_5_marginal_rates.shape

(10000, 404)

In [95]:
syn_1_marginal_rates_cols = list(syn_1_marginal_rates.columns)
syn_2_marginal_rates_cols = list(syn_2_marginal_rates.columns)
syn_3_marginal_rates_cols = list(syn_3_marginal_rates.columns)
syn_4_marginal_rates_cols = list(syn_4_marginal_rates.columns)
syn_5_marginal_rates_cols = list(syn_5_marginal_rates.columns)
syn_6_marginal_rates_cols = list(syn_6_marginal_rates.columns)
syn_7_marginal_rates_cols = list(syn_7_marginal_rates.columns)
syn_8_marginal_rates_cols = list(syn_8_marginal_rates.columns)
syn_9_marginal_rates_cols = list(syn_9_marginal_rates.columns)
syn_10_marginal_rates_cols = list(syn_10_marginal_rates.columns)

# Do all marginal rates except syn_5 have the same columns?
syn_1_marginal_rates_cols == syn_2_marginal_rates_cols == syn_3_marginal_rates_cols == syn_4_marginal_rates_cols == syn_6_marginal_rates_cols == syn_7_marginal_rates_cols == syn_8_marginal_rates_cols == syn_9_marginal_rates_cols == syn_10_marginal_rates_cols



True

In [94]:
# See which cols syn_1_marginal_rates has that syn_5_marginal_rates does not
set(syn_1_marginal_rates_cols) - set(syn_5_marginal_rates_cols)

{'Unnamed: 406', 'l_134', 'm_134', 'r_134'}

In [90]:
# See which cols syn_5_marginal_rates has that syn_1_marginal_rates does not
set(syn_5_marginal_rates_cols) - set(syn_1_marginal_rates_cols)

{'Unnamed: 403'}

Since each column in the marginal_rates.log files should refer to a different time bin, l_134, m_134, and r_134 indicate that syn_5_marginal_rates is missing time bin 134. 

It is also missing column 'Unnamed: 406', but has a column 'Unnamed: 403'. The meaning of the last two are unclear. 

In [81]:
# Syn's mcmc logs all have the same shape
syn_1_mcmc = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_1_C_G_COVhp_BDS_mcmc.log', sep="\t", header=0)
syn_2_mcmc = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_2_C_G_COVhp_BDS_mcmc.log', sep="\t", header=0)
syn_3_mcmc = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_3_C_G_COVhp_BDS_mcmc.log', sep="\t", header=0)
syn_4_mcmc = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_4_C_G_COVhp_BDS_mcmc.log', sep="\t", header=0)
syn_5_mcmc = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_5_C_G_COVhp_BDS_mcmc.log', sep="\t", header=0)
syn_6_mcmc = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_6_C_G_COVhp_BDS_mcmc.log', sep="\t", header=0)
syn_7_mcmc = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_7_C_G_COVhp_BDS_mcmc.log', sep="\t", header=0)
syn_8_mcmc = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_8_C_G_COVhp_BDS_mcmc.log', sep="\t", header=0)
syn_9_mcmc = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_9_C_G_COVhp_BDS_mcmc.log', sep="\t", header=0)
syn_10_mcmc = pd.read_csv('./synapsida/mcmc_fixshift_predictors/C_covar_test/synapsida_pyrate_10_C_G_COVhp_BDS_mcmc.log', sep="\t", header=0)

syn_1_mcmc.shape, syn_2_mcmc.shape, syn_3_mcmc.shape, syn_4_mcmc.shape, syn_5_mcmc.shape, syn_6_mcmc.shape, syn_7_mcmc.shape, syn_8_mcmc.shape, syn_9_mcmc.shape, syn_10_mcmc.shape

((10000, 1104),
 (10000, 1104),
 (10000, 1104),
 (10000, 1104),
 (10000, 1104),
 (10000, 1104),
 (10000, 1104),
 (10000, 1104),
 (10000, 1104),
 (10000, 1104))

In [86]:
syn_5_mcmc.head()

,it,posterior,prior,PP_lik,BD_lik,q_0,q_1,q_2,q_3,q_4,...,Wadiasaurus_TE,Walteria_TE,Wantulignathus_TE,Watongia_TE,Woutersia_TE,Woznikella_TE,Xiyukannemeyeria_TE,Xyrospondylus_TE,Yikezhaogia_TE,Zambiasaurus_TE
0,0,-12168.909686,-141.908714,-8911.095908,-3115.905065,0.638343,0.638343,0.638343,0.638343,0.638343,...,67.855232,86.663088,85.415427,90.717819,30.013760,51.972876,62.554337,128.316199,66.997616,67.190527
1,10000,-10713.427449,-130.838850,-7912.492389,-2670.096210,0.751305,1.187214,0.754184,0.597815,0.951537,...,67.953678,86.537733,85.199805,90.619399,29.798754,50.160059,62.598572,128.351378,67.019762,67.057544
2,20000,-10735.165383,-129.934150,-7927.262741,-2677.968492,0.743480,1.351236,0.767371,0.694401,0.953361,...,67.916347,85.959892,85.321137,89.704392,30.003763,49.771290,62.573433,128.519510,66.978463,67.266459
3,30000,-10685.914055,-133.238170,-7887.090729,-2665.585156,0.941111,1.812508,1.062674,0.775570,1.071058,...,67.943887,84.995955,84.995824,90.042411,29.983006,50.237467,62.527738,126.858118,67.011017,67.159274
4,40000,-10640.196164,-134.049024,-7853.350357,-2652.796782,0.925197,2.479792,1.234428,0.864673,1.186819,...,67.948861,85.746985,84.982121,90.551300,29.986041,51.070751,62.414041,128.878297,66.952819,67.162662


In [88]:
# reran synapdia replicate 5 on ws just to see if the loss of 3 columns was a fluke. Nope, it's consistent across reruns
# Need to check pyrate input file
syn_5_marginal_rates_rerun = pd.read_csv('./synapsida/pyrate_mcmc_logs/synapsida_pyrate_5_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
syn_5_marginal_rates_rerun.shape

(7, 404)

In [89]:
syn_1_marginal_rates_rerun = pd.read_csv('./synapsida/pyrate_mcmc_logs/synapsida_pyrate_1_C_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
syn_1_marginal_rates_rerun.shape

(6, 407)

In [98]:
 # Checking whether all of reptilia's C_covar marginal_rates log files had the same columns
rep_1_marginal_rates = pd.read_csv('./reptilia/mcmc_fixshift_predictors/C_covar/reptilia_pyrate_1_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
rep_2_marginal_rates = pd.read_csv('./reptilia/mcmc_fixshift_predictors/C_covar/reptilia_pyrate_2_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
rep_3_marginal_rates = pd.read_csv('./reptilia/mcmc_fixshift_predictors/C_covar/reptilia_pyrate_3_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
rep_4_marginal_rates = pd.read_csv('./reptilia/mcmc_fixshift_predictors/C_covar/reptilia_pyrate_4_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
rep_5_marginal_rates = pd.read_csv('./reptilia/mcmc_fixshift_predictors/C_covar/reptilia_pyrate_5_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
rep_6_marginal_rates = pd.read_csv('./reptilia/mcmc_fixshift_predictors/C_covar/reptilia_pyrate_6_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
rep_7_marginal_rates = pd.read_csv('./reptilia/mcmc_fixshift_predictors/C_covar/reptilia_pyrate_7_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
rep_8_marginal_rates = pd.read_csv('./reptilia/mcmc_fixshift_predictors/C_covar/reptilia_pyrate_8_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
rep_9_marginal_rates = pd.read_csv('./reptilia/mcmc_fixshift_predictors/C_covar/reptilia_pyrate_9_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)
rep_10_marginal_rates = pd.read_csv('./reptilia/mcmc_fixshift_predictors/C_covar/reptilia_pyrate_10_G_COVhp_BDS_marginal_rates.log', sep="\t", header=0)

# Are all the columns the same?
# Yes
list(rep_1_marginal_rates.columns) == list(rep_2_marginal_rates.columns) == list(rep_3_marginal_rates.columns) == list(rep_4_marginal_rates.columns) == list(rep_5_marginal_rates.columns) == list(rep_6_marginal_rates.columns) == list(rep_7_marginal_rates.columns) == list(rep_8_marginal_rates.columns) == list(rep_9_marginal_rates.columns) == list(rep_10_marginal_rates.columns)

True

# Concat Per_species_rates Issue

The concat version of these files seems to have one more column than the non-concatenated. I hypothesize it's an unnamed column from saving somewhere, which is a hassle considering all the needed reruns

In [74]:
# Reptilia A_bdnn

origin_rep_a_bdnn = pd.read_csv('./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_original_incomplete_logs/reptilia_pyrate_4_G_BDS_BDNN_4_2Tc_per_species_rates.log', sep="\t", header=0)
concat_rep_a_bdnn = pd.read_csv('./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_CONCAT_per_species_rates.log', sep="\t", header=0)

In [76]:
# Which colums are unique to each log
set(list(origin_rep_a_bdnn.columns)) - set(list(concat_rep_a_bdnn.columns)),
set(list(concat_rep_a_bdnn.columns)) - set(list(origin_rep_a_bdnn.columns))
                                           

{'iterations'}

Ah, conclusion: the original version of my final function was mistakenly assuming that the per_species_rates.log had an 'iterations' column. It does not. Edited to remove that, and also edited to change the iterations column in marginal_rates.log to 'it', which is what it was originally called in the original files. 

Note that the unnamed/empty header column ("") in the original marginal_rates.log is default renamed by Python to "Unnamed: 898". When I -combLogRJ (combine replicates' logs) with concatentaed marginal_rates.log files (have the "Unnamed: 898" column) and original marginal_rates.log files (have the unnamed/empty header column ""), this does not pose an issue. All that matters is that the files have the same # of columns

# Ex and Sp Rates Issue 

Concatenating original and restored logs leads to the creation of many new columns (up to 130 new columns) for some reason

In [91]:
sp_rates_concat = pd.read_csv('./reptilia/mcmc_no_predictors/A_bdnn/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_CONCAT_sp_rates.log', sep="\t", header=0)
sp_rates_original = pd.read_csv('./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_original_incomplete_logs/reptilia_pyrate_4_G_BDS_BDNN_4_2Tc_sp_rates.log', sep="\t", header=0)

In [102]:
set(list(sp_rates_concat.columns)) - set(list(sp_rates_original.columns)),
set(list(sp_rates_original.columns)) - set(list(sp_rates_concat.columns))

set()

In [94]:
sp_rates_concat.shape, sp_rates_original.shape

((10475, 362), (9693, 247))

In [100]:
sp_rates_concat.columns.isna().sum(), sp_rates_original.columns.isna().sum()    

(0, 0)

In [101]:
sp_rates_concat.columns

Index(['0.7021791291715602', '0.702179124256164', '0.7021791187087707',
       '0.7021791131613488', '0.7021791076138986', '0.7021791020664202',
       '0.7021790965189137', '0.7021790909713798', '0.7021790854238181',
       '0.7021790798762295',
       ...
       'nan.11', 'nan.12', 'nan.13', 'nan.14', 'nan.15', 'nan.16', 'nan.17',
       'nan.18', 'nan.19', 'nan.20'],
      dtype='object', length=362)

In [99]:
sp_rates_original.columns

Index(['0.7021791291715602', '0.702179124256164', '0.7021791187087707',
       '0.7021791131613488', '0.7021791076138986', '0.7021791020664202',
       '0.7021790965189137', '0.7021790909713798', '0.7021790854238181',
       '0.7021790798762295',
       ...
       '10', '9', '8', '7', '6', '5', '4', '3', '2', '1'],
      dtype='object', length=247)

In [103]:
# Check for duplicate columns in sp_rates_concat
duplicate_columns = sp_rates_concat.columns[sp_rates_concat.columns.duplicated()]
print(duplicate_columns)


Index([], dtype='object')


In [104]:
# Check for whitespace differences
cols_concat = [str(col).strip() for col in sp_rates_concat.columns]
cols_original = [str(col).strip() for col in sp_rates_original.columns]
print(len(set(cols_concat) - set(cols_original)))

# Check column names character by character
for col in sp_rates_concat.columns:
    if col not in sp_rates_original.columns:
        print(f"Column {col!r} is in concat but not in original")
        # Show representation with character codes
        print([ord(c) for c in str(col)])

115
Column '0.6968121308961345' is in concat but not in original
[48, 46, 54, 57, 54, 56, 49, 50, 49, 51, 48, 56, 57, 54, 49, 51, 52, 53]
Column '0.6968121316821227' is in concat but not in original
[48, 46, 54, 57, 54, 56, 49, 50, 49, 51, 49, 54, 56, 50, 49, 50, 50, 55]
Column '0.696812132569168' is in concat but not in original
[48, 46, 54, 57, 54, 56, 49, 50, 49, 51, 50, 53, 54, 57, 49, 54, 56]
Column '0.6968121334562156' is in concat but not in original
[48, 46, 54, 57, 54, 56, 49, 50, 49, 51, 51, 52, 53, 54, 50, 49, 53, 54]
Column '0.696812134343266' is in concat but not in original
[48, 46, 54, 57, 54, 56, 49, 50, 49, 51, 52, 51, 52, 51, 50, 54, 54]
Column '0.6968121352303194' is in concat but not in original
[48, 46, 54, 57, 54, 56, 49, 50, 49, 51, 53, 50, 51, 48, 51, 49, 57, 52]
Column '0.6968121361173754' is in concat but not in original
[48, 46, 54, 57, 54, 56, 49, 50, 49, 51, 54, 49, 49, 55, 51, 55, 53, 52]
Column '0.6968121370044339' is in concat but not in original
[48, 46

In [105]:
# Convert to lists to maintain order
cols_concat = list(sp_rates_concat.columns)
cols_original = list(sp_rates_original.columns)

# Find columns that are in concat but not in original
extra_cols = [col for col in cols_concat if col not in cols_original]
print(f"Number of extra columns: {len(extra_cols)}")
print("First few extra columns:", extra_cols[:5])

Number of extra columns: 115
First few extra columns: ['0.6968121308961345', '0.6968121316821227', '0.696812132569168', '0.6968121334562156', '0.696812134343266']


In [107]:
sp_rates_restored = pd.read_csv('./reptilia/mcmc_no_predictors/A_bdnn/A_bdnn_restored_logs/reptilia_pyrate_4_A_G_BDS_BDNN_4_2Tc_sp_rates.log', sep="\t", header=0)
sp_rates_restored.shape

(783, 247)

In [109]:
set(list(sp_rates_restored.columns)) - set(list(sp_rates_original.columns)),
set(list(sp_rates_original.columns)) - set(list(sp_rates_restored.columns))

{'0.7021784972747648',
 '0.702178502823899',
 '0.7021785083730308',
 '0.7021785139221598',
 '0.702178519471286',
 '0.702178525020409',
 '0.7021785305695285',
 '0.7021785361186446',
 '0.7021785416677566',
 '0.7021785472168645',
 '0.7021785527659682',
 '0.7021785583150673',
 '0.7021785638641613',
 '0.7021785694132504',
 '0.7021785749623342',
 '0.7021785805114129',
 '0.7021785860604853',
 '0.7021785916095518',
 '0.7021785971586121',
 '0.7021786027076662',
 '0.7021786082567133',
 '0.7021786138057536',
 '0.7021786193547864',
 '0.7021786249038121',
 '0.7021786304528304',
 '0.7021786360018403',
 '0.7021786415508423',
 '0.7021786470998358',
 '0.702178652648821',
 '0.7021786581977971',
 '0.7021786637467647',
 '0.7021786692957223',
 '0.7021786748446707',
 '0.7021786803936093',
 '0.7021786859425381',
 '0.7021786914914562',
 '0.702178697040364',
 '0.7021787025892612',
 '0.7021787081381471',
 '0.702178713687022',
 '0.7021787192358858',
 '0.7021787247847378',
 '0.7021787303335778',
 '0.7021787358824

In [111]:
sp_rates_concat_B = pd.read_csv('synapsida/mcmc_predictors/B_bdnn_stdscaled_boxcox/synapsida_pyrate_1_B_stdscaled_boxcox_G_BDS_BDNN_16_8TVc_CONCAT_sp_rates.log', sep="\t", header=0)
sp_rates_orig_B = pd.read_csv('synapsida/mcmc_predictors/B_bdnn_stdscaled_boxcox/B_bdnn_stdscaled_boxcox_original_incomplete_logs/synapsida_pyrate_1_B_stdscaled_boxcox_G_BD1-1_BDNN_16_8TVc_sp_rates.log', sep="\t", header=0)
sp_rates_concat_B.shape, sp_rates_orig_B.shape

((20000, 387), (6785, 269))

In [112]:
concat_columns_stripped = sp_rates_concat.columns.str.strip()
original_columns_stripped = sp_rates_original.columns.str.strip()

# Check the difference again
difference = set(concat_columns_stripped) - set(original_columns_stripped)
print(difference)

{'0.696812145875162', '0.6968122017653957', '0.6968122106373693', '0.6968121582945831', '0.6968121503106183', 'nan.18', '0.6968121538590251', '0.6968121308961345', '0.6968122186222115', '0.6968122132989775', '0.6968121565203536', '0.6968122159605915', '0.6968121352303194', '0.6968121467622485', '0.6968121946678872', '0.6968121813602697', '0.6968121937807036', '0.6968122177350042', '0.6968122203966275', '0.6968121840217681', '0.6968121999910123', '0.6968122195094193', '0.6968122088629678', '0.6968121884576282', '0.6968121902319814', '0.696812144988078', '0.6968121627301941', '0.6968121494235223', '0.6968121822474344', '0.696812205314175', '0.6968121511977166', '0.696812189344804', '0.6968121432139169', '0.6968121370044339', '0.6968121600688212', '0.6968121831346007', '0.6968122079757683', '0.6968121751501597', '0.69681215297192', '0.6968121716015622', '0.6968121964422577', '0.6968122008782041', '0.6968121795859448', 'nan.12', '0.6968121982166325', '0.6968122150733864', '0.69681220708856

In [114]:
len(difference)

115